export type TerrariaBuffType = 'Buff' | 'Debuff'

export interface TerrariaBuff {
  id: number
  name: string
  internalName: string
  type: TerrariaBuffType
  zh?: string
}

// Based on the official Terraria Wiki Buff IDs table. The panel still allows custom ID input
// because modded servers and newer Terraria builds may expose IDs not listed here.
export const TERRARIA_BUFFS: TerrariaBuff[] = [
  { id: 1, name: 'Obsidian Skin', internalName: 'ObsidianSkin', type: 'Buff', zh: '黑曜石皮' },
  { id: 2, name: 'Regeneration', internalName: 'Regeneration', type: 'Buff', zh: '再生' },
  { id: 3, name: 'Swiftness', internalName: 'Swiftness', type: 'Buff', zh: '敏捷' },
  { id: 4, name: 'Gills', internalName: 'Gills', type: 'Buff', zh: '鱼鳃' },
  { id: 5, name: 'Ironskin', internalName: 'Ironskin', type: 'Buff', zh: '铁皮' },
  { id: 6, name: 'Mana Regeneration', internalName: 'ManaRegeneration', type: 'Buff', zh: '魔力再生' },
  { id: 7, name: 'Magic Power', internalName: 'MagicPower', type: 'Buff', zh: '魔能' },
  { id: 8, name: 'Featherfall', internalName: 'Featherfall', type: 'Buff', zh: '羽落' },
  { id: 9, name: 'Spelunker', internalName: 'Spelunker', type: 'Buff', zh: '洞穴探险' },
  { id: 10, name: 'Invisibility', internalName: 'Invisibility', type: 'Buff', zh: '隐身' },
  { id: 11, name: 'Shine', internalName: 'Shine', type: 'Buff', zh: '光芒' },
  { id: 12, name: 'Night Owl', internalName: 'NightOwl', type: 'Buff', zh: '夜猫子' },
  { id: 13, name: 'Battle', internalName: 'Battle', type: 'Buff', zh: '战斗' },
  { id: 14, name: 'Thorns', internalName: 'Thorns', type: 'Buff', zh: '荆棘' },
  { id: 15, name: 'Water Walking', internalName: 'WaterWalking', type: 'Buff', zh: '水上漂' },
  { id: 16, name: 'Archery', internalName: 'Archery', type: 'Buff', zh: '箭术' },
  { id: 17, name: 'Hunter', internalName: 'Hunter', type: 'Buff', zh: '猎人' },
  { id: 18, name: 'Gravitation', internalName: 'Gravitation', type: 'Buff', zh: '重力' },
  { id: 19, name: 'Shadow Orb', internalName: 'ShadowOrb', type: 'Buff', zh: '暗影珠' },
  { id: 20, name: 'Poisoned', internalName: 'Poisoned', type: 'Debuff', zh: '中毒' },
  { id: 21, name: 'Potion Sickness', internalName: 'PotionSickness', type: 'Debuff', zh: '耐药性' },
  { id: 22, name: 'Darkness', internalName: 'Darkness', type: 'Debuff', zh: '黑暗' },
  { id: 23, name: 'Cursed', internalName: 'Cursed', type: 'Debuff', zh: '诅咒' },
  { id: 24, name: 'On Fire!', internalName: 'OnFire', type: 'Debuff', zh: '着火了！' },
  { id: 25, name: 'Tipsy', internalName: 'Tipsy', type: 'Debuff', zh: '踉跄' },
  { id: 26, name: 'Well Fed', internalName: 'WellFed', type: 'Buff', zh: '吃得好' },
  { id: 27, name: 'Fairy (Blue)', internalName: 'FairyBlue', type: 'Buff', zh: '仙灵' },
  { id: 28, name: 'Werewolf', internalName: 'Werewolf', type: 'Buff', zh: '狼人' },
  { id: 29, name: 'Clairvoyance', internalName: 'Clairvoyance', type: 'Buff', zh: '灵视' },
  { id: 30, name: 'Bleeding', internalName: 'Bleeding', type: 'Debuff', zh: '流血' },
  { id: 31, name: 'Confused', internalName: 'Confused', type: 'Debuff', zh: '困惑' },
  { id: 32, name: 'Slow', internalName: 'Slow', type: 'Debuff', zh: '缓慢' },
  { id: 33, name: 'Weak', internalName: 'Weak', type: 'Debuff', zh: '虚弱' },
  { id: 34, name: 'Merfolk', internalName: 'Merfolk', type: 'Buff', zh: '人鱼' },
  { id: 35, name: 'Silenced', internalName: 'Silenced', type: 'Debuff', zh: '沉默' },
  { id: 36, name: 'Broken Armor', internalName: 'BrokenArmor', type: 'Debuff', zh: '破损盔甲' },
  { id: 37, name: 'Horrified', internalName: 'Horrified', type: 'Debuff', zh: '惊恐' },
  { id: 38, name: 'The Tongue', internalName: 'TheTongue', type: 'Debuff', zh: '狂卷之舌' },
  { id: 39, name: 'Cursed Inferno', internalName: 'CursedInferno', type: 'Debuff', zh: '诅咒狱火' },
  { id: 40, name: 'Pet Bunny', internalName: 'PetBunny', type: 'Buff', zh: '宠物兔兔' },
  { id: 41, name: 'Baby Penguin', internalName: 'BabyPenguin', type: 'Buff', zh: '企鹅宝宝' },
  { id: 42, name: 'Pet Turtle', internalName: 'PetTurtle', type: 'Buff', zh: '宠物海龟' },
  { id: 43, name: "Paladin's Shield", internalName: 'PaladinsShield', type: 'Buff', zh: '圣骑士护盾' },
  { id: 44, name: 'Frostburn', internalName: 'Frostburn', type: 'Debuff', zh: '霜冻' },
  { id: 45, name: 'Baby Eater', internalName: 'BabyEater', type: 'Buff', zh: '吞噬怪宝宝' },
  { id: 46, name: 'Chilled', internalName: 'Chilled', type: 'Debuff', zh: '冷冻' },
  { id: 47, name: 'Frozen', internalName: 'Frozen', type: 'Debuff', zh: '冰冻' },
  { id: 48, name: 'Honey', internalName: 'Honey', type: 'Buff', zh: '蜂蜜' },
  { id: 49, name: 'Pygmies', internalName: 'Pygmies', type: 'Buff', zh: '矮人' },
  { id: 50, name: 'Baby Skeletron Head', internalName: 'BabySkeletronHead', type: 'Buff', zh: '骷髅王头宝宝' },
  { id: 51, name: 'Baby Hornet', internalName: 'BabyHornet', type: 'Buff', zh: '黄蜂宝宝' },
  { id: 52, name: 'Tiki Spirit', internalName: 'TikiSpirit', type: 'Buff', zh: '提基幽魂' },
  { id: 53, name: 'Pet Lizard', internalName: 'PetLizard', type: 'Buff', zh: '宠物蜥蜴' },
  { id: 54, name: 'Pet Parrot', internalName: 'PetParrot', type: 'Buff', zh: '宠物鹦鹉' },
  { id: 55, name: 'Baby Truffle', internalName: 'BabyTruffle', type: 'Buff', zh: '松露人宝宝' },
  { id: 56, name: 'Pet Sapling', internalName: 'PetSapling', type: 'Buff', zh: '宠物树苗' },
  { id: 57, name: 'Wisp', internalName: 'Wisp', type: 'Buff', zh: '妖灵' },
  { id: 58, name: 'Rapid Healing', internalName: 'RapidHealing', type: 'Buff', zh: '快速治疗' },
  { id: 59, name: 'Holy Protection', internalName: 'ShadowDodge', type: 'Buff', zh: '神圣防护' },
  { id: 60, name: 'Leaf Crystal', internalName: 'LeafCrystal', type: 'Buff', zh: '叶状水晶' },
  { id: 61, name: 'Baby Dinosaur', internalName: 'BabyDinosaur', type: 'Buff', zh: '恐龙宝宝' },
  { id: 62, name: 'Ice Barrier', internalName: 'IceBarrier', type: 'Buff', zh: '冰障' },
  { id: 63, name: 'Panic!', internalName: 'Panic', type: 'Buff', zh: '恐慌！' },
  { id: 64, name: 'Baby Slime', internalName: 'BabySlime', type: 'Buff', zh: '史莱姆宝宝' },
  { id: 65, name: 'Eyeball Spring', internalName: 'EyeballSpring', type: 'Buff', zh: '弹簧眼' },
  { id: 66, name: 'Baby Snowman', internalName: 'BabySnowman', type: 'Buff', zh: '雪人宝宝' },
  { id: 67, name: 'Burning', internalName: 'Burning', type: 'Debuff', zh: '燃烧' },
  { id: 68, name: 'Suffocation', internalName: 'Suffocation', type: 'Debuff', zh: '窒息' },
  { id: 69, name: 'Ichor', internalName: 'Ichor', type: 'Debuff', zh: '灵液' },
  { id: 70, name: 'Acid Venom', internalName: 'Venom', type: 'Debuff', zh: '酸性毒液' },
  { id: 71, name: 'Weapon Imbue: Acid Venom', internalName: 'WeaponImbueVenom', type: 'Buff', zh: '武器灌注：酸性毒液' },
  { id: 72, name: 'Midas', internalName: 'Midas', type: 'Debuff', zh: '迈达斯' },
  { id: 73, name: 'Weapon Imbue: Cursed Flames', internalName: 'WeaponImbueCursedFlames', type: 'Buff', zh: '武器灌注：诅咒焰' },
  { id: 74, name: 'Weapon Imbue: Fire', internalName: 'WeaponImbueFire', type: 'Buff', zh: '武器灌注：火焰' },
  { id: 75, name: 'Weapon Imbue: Gold', internalName: 'WeaponImbueGold', type: 'Buff', zh: '武器灌注：金' },
  { id: 76, name: 'Weapon Imbue: Ichor', internalName: 'WeaponImbueIchor', type: 'Buff', zh: '武器灌注：灵液' },
  { id: 77, name: 'Weapon Imbue: Nanites', internalName: 'WeaponImbueNanites', type: 'Buff', zh: '武器灌注：纳米机器人' },
  { id: 78, name: 'Weapon Imbue: Confetti', internalName: 'WeaponImbueConfetti', type: 'Buff', zh: '武器灌注：彩纸' },
  { id: 79, name: 'Weapon Imbue: Poison', internalName: 'WeaponImbuePoison', type: 'Buff', zh: '武器灌注：毒药' },
  { id: 80, name: 'Blackout', internalName: 'Blackout', type: 'Debuff', zh: '黑视' },
  { id: 81, name: 'Pet Spider', internalName: 'PetSpider', type: 'Buff', zh: '宠物蜘蛛' },
  { id: 82, name: 'Squashling', internalName: 'Squashling', type: 'Buff', zh: '南瓜娃娃' },
  { id: 83, name: 'Ravens', internalName: 'Ravens', type: 'Buff', zh: '乌鸦' },
  { id: 84, name: 'Black Cat', internalName: 'BlackCat', type: 'Buff', zh: '黑猫' },
  { id: 85, name: 'Cursed Sapling', internalName: 'CursedSapling', type: 'Buff', zh: '诅咒树苗' },
  { id: 86, name: 'Water Candle', internalName: 'WaterCandle', type: 'Debuff', zh: '水蜡烛' },
  { id: 87, name: 'Cozy Fire', internalName: 'Campfire', type: 'Buff', zh: '温馨之火' },
  { id: 88, name: 'Chaos State', internalName: 'ChaosState', type: 'Debuff', zh: '混沌状态' },
  { id: 89, name: 'Heart Lamp', internalName: 'HeartLamp', type: 'Buff', zh: '心灯' },
  { id: 90, name: 'Rudolph', internalName: 'Rudolph', type: 'Buff', zh: '鲁道夫' },
  { id: 91, name: 'Puppy', internalName: 'Puppy', type: 'Buff', zh: '小狗' },
  { id: 92, name: 'Baby Grinch', internalName: 'BabyGrinch', type: 'Buff', zh: '格林奇宝宝' },
  { id: 93, name: 'Ammo Box', internalName: 'AmmoBox', type: 'Buff', zh: '弹药箱' },
  { id: 94, name: 'Mana Sickness', internalName: 'ManaSickness', type: 'Debuff', zh: '耐魔性' },
  { id: 95, name: 'Beetle Endurance (15%)', internalName: 'BeetleEndurance1', type: 'Buff', zh: '甲虫耐力' },
  { id: 96, name: 'Beetle Endurance (30%)', internalName: 'BeetleEndurance2', type: 'Buff', zh: '甲虫耐力' },
  { id: 97, name: 'Beetle Endurance (45%)', internalName: 'BeetleEndurance3', type: 'Buff', zh: '甲虫耐力' },
  { id: 98, name: 'Beetle Might (10%)', internalName: 'BeetleMight1', type: 'Buff', zh: '甲虫力量' },
  { id: 99, name: 'Beetle Might (20%)', internalName: 'BeetleMight2', type: 'Buff', zh: '甲虫力量' },
  { id: 100, name: 'Beetle Might (30%)', internalName: 'BeetleMight3', type: 'Buff', zh: '甲虫力量' },
  { id: 101, name: 'Fairy (Red)', internalName: 'FairyRed', type: 'Buff', zh: '仙灵' },
  { id: 102, name: 'Fairy (Green)', internalName: 'FairyGreen', type: 'Buff', zh: '仙灵' },
  { id: 103, name: 'Wet', internalName: 'Wet', type: 'Debuff', zh: '潮湿' },
  { id: 104, name: 'Mining', internalName: 'Mining', type: 'Buff', zh: '挖矿' },
  { id: 105, name: 'Heartreach', internalName: 'Heartreach', type: 'Buff', zh: '拾心' },
  { id: 106, name: 'Calm', internalName: 'Calm', type: 'Buff', zh: '冷静' },
  { id: 107, name: 'Builder', internalName: 'Builder', type: 'Buff', zh: '建筑工' },
  { id: 108, name: 'Titan', internalName: 'Titan', type: 'Buff', zh: '泰坦' },
  { id: 109, name: 'Flipper', internalName: 'Flipper', type: 'Buff', zh: '脚蹼' },
  { id: 110, name: 'Summoning', internalName: 'Summoning', type: 'Buff', zh: '召唤' },
  { id: 111, name: 'Dangersense', internalName: 'Dangersense', type: 'Buff', zh: '危险感' },
  { id: 112, name: 'Ammo Reservation', internalName: 'AmmoReservation', type: 'Buff', zh: '弹药储备' },
  { id: 113, name: 'Lifeforce', internalName: 'Lifeforce', type: 'Buff', zh: '生命力' },
  { id: 114, name: 'Endurance', internalName: 'Endurance', type: 'Buff', zh: '耐力' },
  { id: 115, name: 'Rage', internalName: 'Rage', type: 'Buff', zh: '暴怒' },
  { id: 116, name: 'Inferno', internalName: 'Inferno', type: 'Buff', zh: '狱火' },
  { id: 117, name: 'Wrath', internalName: 'Wrath', type: 'Buff', zh: '怒气' },
  { id: 118, name: 'Minecart', internalName: 'Minecart', type: 'Buff', zh: '矿车' },
  { id: 119, name: 'Lovestruck', internalName: 'Lovestruck', type: 'Debuff', zh: '热恋' },
  { id: 120, name: 'Stinky', internalName: 'Stinky', type: 'Debuff', zh: '恶臭' },
  { id: 121, name: 'Fishing', internalName: 'Fishing', type: 'Buff', zh: '钓鱼' },
  { id: 122, name: 'Sonar', internalName: 'Sonar', type: 'Buff', zh: '声呐' },
  { id: 123, name: 'Crate', internalName: 'Crate', type: 'Buff', zh: '宝匣' },
  { id: 124, name: 'Warmth', internalName: 'Warmth', type: 'Buff', zh: '温暖' },
  { id: 125, name: 'Hornet', internalName: 'HornetMinion', type: 'Buff', zh: '黄蜂' },
  { id: 126, name: 'Imp', internalName: 'ImpMinion', type: 'Buff', zh: '小鬼' },
  { id: 127, name: 'Zephyr Fish', internalName: 'ZephyrFish', type: 'Buff', zh: '和风鱼' },
  { id: 128, name: 'Bunny Mount', internalName: 'BunnyMount', type: 'Buff', zh: '兔兔坐骑' },
  { id: 129, name: 'Pigron Mount', internalName: 'PigronMount', type: 'Buff', zh: '猪龙坐骑' },
  { id: 130, name: 'Slime Mount', internalName: 'SlimeMount', type: 'Buff', zh: '史莱姆坐骑' },
  { id: 131, name: 'Turtle Mount', internalName: 'TurtleMount', type: 'Buff', zh: '海龟坐骑' },
  { id: 132, name: 'Bee Mount', internalName: 'BeeMount', type: 'Buff', zh: '蜜蜂坐骑' },
  { id: 133, name: 'Spider', internalName: 'SpiderMinion', type: 'Buff', zh: '蜘蛛' },
  { id: 134, name: 'Twins', internalName: 'TwinEyesMinion', type: 'Buff', zh: '双子魔眼' },
  { id: 135, name: 'Pirate', internalName: 'PirateMinion', type: 'Buff', zh: '海盗' },
  { id: 136, name: 'Faun', internalName: 'MiniMinotaur', type: 'Buff', zh: '法翁' },
  { id: 137, name: 'Slime', internalName: 'Slimed', type: 'Debuff', zh: '黏液' },
  { id: 138, name: 'Minecart (Legacy Unused)', internalName: 'MinecartLegacyUnused', type: 'Buff' },
  { id: 139, name: 'Sharknado', internalName: 'SharknadoMinion', type: 'Buff', zh: '鲨鱼旋风' },
  { id: 140, name: 'UFO', internalName: 'UFOMinion', type: 'Buff', zh: 'UFO' },
  { id: 141, name: 'UFO Mount', internalName: 'UFOMount', type: 'Buff', zh: 'UFO坐骑' },
  { id: 142, name: 'Drill Mount', internalName: 'DrillMount', type: 'Buff', zh: '钻头坐骑' },
  { id: 143, name: 'Scutlix Mount', internalName: 'ScutlixMount', type: 'Buff', zh: '鳞甲怪坐骑' },
  { id: 144, name: 'Electrified', internalName: 'Electrified', type: 'Debuff', zh: '带电' },
  { id: 145, name: 'Moon Bite', internalName: 'MoonLeech', type: 'Debuff', zh: '月噬' },
  { id: 146, name: 'Happy!', internalName: 'Sunflower', type: 'Buff', zh: '快乐！' },
  { id: 147, name: 'Banner', internalName: 'MonsterBanner', type: 'Buff', zh: '旗帜' },
  { id: 148, name: 'Feral Bite', internalName: 'Rabies', type: 'Debuff', zh: '野性咬噬' },
  { id: 149, name: 'Webbed', internalName: 'Webbed', type: 'Debuff', zh: '被网住' },
  { id: 150, name: 'Bewitched', internalName: 'Bewitched', type: 'Buff', zh: '着魔' },
  { id: 151, name: 'Life Drain', internalName: 'SoulDrain', type: 'Buff', zh: '夺命杖' },
  { id: 152, name: 'Magic Lantern', internalName: 'MagicLantern', type: 'Buff', zh: '魔法灯笼' },
  { id: 153, name: 'Shadowflame', internalName: 'ShadowFlame', type: 'Debuff', zh: '暗影焰' },
  { id: 154, name: 'Baby Face Monster', internalName: 'BabyFaceMonster', type: 'Buff', zh: '脸怪宝宝' },
  { id: 155, name: 'Crimson Heart', internalName: 'CrimsonHeart', type: 'Buff', zh: '猩红之心' },
  { id: 156, name: 'Stoned', internalName: 'Stoned', type: 'Debuff', zh: '石化' },
  { id: 157, name: 'Peace Candle', internalName: 'PeaceCandle', type: 'Buff', zh: '和平蜡烛' },
  { id: 158, name: 'Star in a Bottle', internalName: 'StarInBottle', type: 'Buff', zh: '星星瓶' },
  { id: 159, name: 'Sharpened', internalName: 'Sharpened', type: 'Buff', zh: '锋利' },
  { id: 160, name: 'Dazed', internalName: 'Dazed', type: 'Debuff', zh: '眩晕' },
  { id: 161, name: 'Deadly Sphere', internalName: 'DeadlySphere', type: 'Buff', zh: '致命球' },
  { id: 162, name: 'Unicorn Mount', internalName: 'UnicornMount', type: 'Buff', zh: '独角兽坐骑' },
  { id: 163, name: 'Obstructed', internalName: 'Obstructed', type: 'Debuff', zh: '遮挡' },
  { id: 164, name: 'Distorted', internalName: 'VortexDebuff', type: 'Debuff', zh: '扭曲' },
  { id: 165, name: "Dryad's Blessing", internalName: 'DryadsWard', type: 'Buff', zh: '树妖祝福' },
  { id: 166, name: 'Minecart (Mechanical)', internalName: 'MinecartMech', type: 'Buff', zh: '矿车' },
  { id: 167, name: 'Minecart (Mechanical Legacy Unused)', internalName: 'MinecartMechLegacyUnused', type: 'Buff' },
  { id: 168, name: 'Cute Fishron Mount', internalName: 'CuteFishronMount', type: 'Buff', zh: '可爱猪龙鱼坐骑' },
  { id: 169, name: 'Penetrated', internalName: 'BoneJavelin', type: 'Debuff', zh: '穿透' },
  { id: 170, name: 'Solar Blaze (1 stack)', internalName: 'SolarShield1', type: 'Buff', zh: '日耀烈焰' },
  { id: 171, name: 'Solar Blaze (2 stacks)', internalName: 'SolarShield2', type: 'Buff', zh: '日耀烈焰' },
  { id: 172, name: 'Solar Blaze (3 stacks)', internalName: 'SolarShield3', type: 'Buff', zh: '日耀烈焰' },
  { id: 173, name: 'Life Nebula (1 stack)', internalName: 'NebulaUpLife1', type: 'Buff', zh: '生命星云' },
  { id: 174, name: 'Life Nebula (2 stacks)', internalName: 'NebulaUpLife2', type: 'Buff', zh: '生命星云' },
  { id: 175, name: 'Life Nebula (3 stacks)', internalName: 'NebulaUpLife3', type: 'Buff', zh: '生命星云' },
  { id: 176, name: 'Mana Nebula (1 stack)', internalName: 'NebulaUpMana1', type: 'Buff', zh: '魔力星云' },
  { id: 177, name: 'Mana Nebula (2 stacks)', internalName: 'NebulaUpMana2', type: 'Buff', zh: '魔力星云' },
  { id: 178, name: 'Mana Nebula (3 stacks)', internalName: 'NebulaUpMana3', type: 'Buff', zh: '魔力星云' },
  { id: 179, name: 'Damage Nebula (1 stack)', internalName: 'NebulaUpDmg1', type: 'Buff', zh: '伤害星云' },
  { id: 180, name: 'Damage Nebula (2 stacks)', internalName: 'NebulaUpDmg2', type: 'Buff', zh: '伤害星云' },
  { id: 181, name: 'Damage Nebula (3 stacks)', internalName: 'NebulaUpDmg3', type: 'Buff', zh: '伤害星云' },
  { id: 182, name: 'Stardust Cell (Stardust Minion)', internalName: 'StardustMinion', type: 'Buff', zh: '星尘细胞' },
  { id: 183, name: 'Celled', internalName: 'StardustMinionBleed', type: 'Debuff', zh: '细胞附着' },
  { id: 184, name: 'Minecart (Wooden)', internalName: 'MinecartWood', type: 'Buff', zh: '矿车' },
  { id: 185, name: 'Minecart (Wood Legacy Unused)', internalName: 'MinecartWoodLegacyUnused', type: 'Buff' },
  { id: 186, name: "Dryad's Bane", internalName: 'DryadsWardDebuff', type: 'Debuff', zh: '树妖祸害' },
  { id: 187, name: 'Stardust Guardian', internalName: 'StardustGuardianMinion', type: 'Buff', zh: '星尘守卫' },
  { id: 188, name: 'Stardust Dragon', internalName: 'StardustDragonMinion', type: 'Buff', zh: '星尘之龙' },
  { id: 189, name: 'Daybroken', internalName: 'Daybreak', type: 'Debuff', zh: '破晓' },
  { id: 190, name: 'Suspicious Looking Eye', internalName: 'SuspiciousTentacle', type: 'Buff', zh: '可疑眼球' },
  { id: 191, name: 'Companion Cube', internalName: 'CompanionCube', type: 'Buff', zh: '同伴方块' },
  { id: 192, name: 'Sugar Rush', internalName: 'SugarRush', type: 'Buff', zh: '糖果冲刺' },
  { id: 193, name: 'Basilisk Mount', internalName: 'BasiliskMount', type: 'Buff', zh: '蛇蜥怪坐骑' },
  { id: 194, name: 'Mighty Wind', internalName: 'WindPushed', type: 'Debuff', zh: '强风' },
  { id: 195, name: 'Withered Armor', internalName: 'WitheredArmor', type: 'Debuff', zh: '枯萎盔甲' },
  { id: 196, name: 'Withered Weapon', internalName: 'WitheredWeapon', type: 'Debuff', zh: '枯萎武器' },
  { id: 197, name: 'Oozed', internalName: 'OgreSpit', type: 'Debuff', zh: '分泌物' },
  { id: 198, name: 'Striking Moment', internalName: 'ParryDamageBuff', type: 'Buff', zh: '惊人一刻' },
  { id: 199, name: 'Creative Shock', internalName: 'NoBuilding', type: 'Debuff', zh: '创意震撼' },
  { id: 200, name: 'Propeller Gato', internalName: 'PetDD2Gato', type: 'Buff', zh: '飞翔Gato' },
  { id: 201, name: 'Flickerwick', internalName: 'PetDD2Ghost', type: 'Buff', zh: '闪烁灯芯' },
  { id: 202, name: 'Hoardagron', internalName: 'PetDD2Dragon', type: 'Buff', zh: 'Hoardagron' },
  { id: 203, name: "Betsy's Curse", internalName: 'BetsysCurse', type: 'Debuff', zh: '双足翼龙诅咒' },
  { id: 204, name: 'Oiled', internalName: 'Oiled', type: 'Debuff', zh: '涂油' },
  { id: 205, name: 'Ballista Panic!', internalName: 'BallistaPanic', type: 'Buff', zh: '弩车恐慌！' },
  { id: 206, name: 'Plenty Satisfied', internalName: 'WellFed2', type: 'Buff', zh: '很满意' },
  { id: 207, name: 'Exquisitely Stuffed', internalName: 'WellFed3', type: 'Buff', zh: '酒足饭饱' },
  { id: 208, name: 'Minecart (Desert)', internalName: 'DesertMinecart', type: 'Buff', zh: '矿车' },
  { id: 209, name: 'Minecart (Desert Legacy Unused)', internalName: 'DesertMinecartLegacyUnused', type: 'Buff' },
  { id: 210, name: 'Minecart (Minecarp)', internalName: 'FishMinecart', type: 'Buff', zh: '矿车' },
  { id: 211, name: 'Minecart (Minecarp Legacy Unused)', internalName: 'FishMinecartLegacyUnused', type: 'Buff' },
  { id: 212, name: 'Golf Cart', internalName: 'GolfCartMount', type: 'Buff', zh: '高尔夫球车' },
  { id: 213, name: 'Sanguine Bat', internalName: 'BatOfLight', type: 'Buff', zh: '血红蝙蝠' },
  { id: 214, name: 'Vampire Frog', internalName: 'VampireFrog', type: 'Buff', zh: '吸血鬼青蛙' },
  { id: 215, name: 'The Bast Defense', internalName: 'CatBast', type: 'Buff', zh: '巴斯特防御' },
  { id: 216, name: 'Baby Finch', internalName: 'BabyBird', type: 'Buff', zh: '雀宝宝' },
  { id: 217, name: 'Estee', internalName: 'UpbeatStar', type: 'Buff', zh: '埃斯蒂' },
  { id: 218, name: 'Sugar Glider', internalName: 'SugarGlider', type: 'Buff', zh: '蜜袋鼯' },
  { id: 219, name: 'Shark Pup', internalName: 'SharkPup', type: 'Buff', zh: '小鲨鱼' },
  { id: 220, name: 'Minecart (Bee)', internalName: 'BeeMinecart', type: 'Buff', zh: '矿车' },
  { id: 221, name: 'Minecart (Bee Legacy Unused)', internalName: 'BeeMinecartLegacyUnused', type: 'Buff' },
  { id: 222, name: 'Minecart (Ladybug)', internalName: 'LadybugMinecart', type: 'Buff', zh: '矿车' },
  { id: 223, name: 'Minecart (Ladybug Legacy Unused)', internalName: 'LadybugMinecartLegacyUnused', type: 'Buff' },
  { id: 224, name: 'Minecart (Pigron)', internalName: 'PigronMinecart', type: 'Buff', zh: '矿车' },
  { id: 225, name: 'Minecart (Pigron Legacy Unused)', internalName: 'PigronMinecartLegacyUnused', type: 'Buff' },
  { id: 226, name: 'Minecart (Sunflower)', internalName: 'SunflowerMinecart', type: 'Buff', zh: '矿车' },
  { id: 227, name: 'Minecart (Sunflower Legacy Unused)', internalName: 'SunflowerMinecartLegacyUnused', type: 'Buff' },
  { id: 228, name: 'Minecart (Demonic Hellcart)', internalName: 'HellMinecart', type: 'Buff', zh: '矿车' },
  { id: 229, name: 'Minecart (Hellcart Legacy Unused)', internalName: 'HellMinecartLegacyUnused', type: 'Buff' },
  { id: 230, name: "Witch's Broom", internalName: 'WitchBroom', type: 'Buff', zh: '女巫扫帚' },
  { id: 231, name: 'Minecart (Shroom)', internalName: 'ShroomMinecart', type: 'Buff', zh: '矿车' },
  { id: 232, name: 'Minecart (Shroom Legacy Unused)', internalName: 'ShroomMinecartLegacyUnused', type: 'Buff' },
  { id: 233, name: 'Minecart (Amethyst)', internalName: 'AmethystMinecart', type: 'Buff', zh: '矿车' },
  { id: 234, name: 'Minecart (Amethyst Legacy Unused)', internalName: 'AmethystMinecartLegacyUnused', type: 'Buff' },
  { id: 235, name: 'Minecart (Topaz)', internalName: 'TopazMinecart', type: 'Buff', zh: '矿车' },
  { id: 236, name: 'Minecart (Topaz Legacy Unused)', internalName: 'TopazMinecartLegacyUnused', type: 'Buff' },
  { id: 237, name: 'Minecart (Sapphire)', internalName: 'SapphireMinecart', type: 'Buff', zh: '矿车' },
  { id: 238, name: 'Minecart (Sapphire Legacy Unused)', internalName: 'SapphireMinecartLegacyUnused', type: 'Buff' },
  { id: 239, name: 'Minecart (Emerald)', internalName: 'EmeraldMinecart', type: 'Buff', zh: '矿车' },
  { id: 240, name: 'Minecart (Emerald Legacy Unused)', internalName: 'EmeraldMinecartLegacyUnused', type: 'Buff' },
  { id: 241, name: 'Minecart (Ruby)', internalName: 'RubyMinecart', type: 'Buff', zh: '矿车' },
  { id: 242, name: 'Minecart (Ruby Legacy Unused)', internalName: 'RubyMinecartLegacyUnused', type: 'Buff' },
  { id: 243, name: 'Minecart (Diamond)', internalName: 'DiamondMinecart', type: 'Buff', zh: '矿车' },
  { id: 244, name: 'Minecart (Diamond Legacy Unused)', internalName: 'DiamondMinecartLegacyUnused', type: 'Buff' },
  { id: 245, name: 'Minecart (Amber)', internalName: 'AmberMinecart', type: 'Buff', zh: '矿车' },
  { id: 246, name: 'Minecart (Amber Legacy Unused)', internalName: 'AmberMinecartLegacyUnused', type: 'Buff' },
  { id: 247, name: 'Minecart (Beetle)', internalName: 'BeetleMinecart', type: 'Buff', zh: '矿车' },
  { id: 248, name: 'Minecart (Beetle Legacy Unused)', internalName: 'BeetleMinecartLegacyUnused', type: 'Buff' },
  { id: 249, name: 'Minecart (Meowmere)', internalName: 'MeowmereMinecart', type: 'Buff', zh: '矿车' },
  { id: 250, name: 'Minecart (Meowmere Legacy Unused)', internalName: 'MeowmereMinecartLegacyUnused', type: 'Buff' },
  { id: 251, name: 'Minecart (Party)', internalName: 'PartyMinecart', type: 'Buff', zh: '矿车' },
  { id: 252, name: 'Minecart (Party Legacy Unused)', internalName: 'PartyMinecartLegacyUnused', type: 'Buff' },
  { id: 253, name: 'Minecart (The Dutchman)', internalName: 'PirateMinecart', type: 'Buff', zh: '矿车' },
  { id: 254, name: 'Minecart (Pirate Legacy Unused)', internalName: 'PirateMinecartLegacyUnused', type: 'Buff' },
  { id: 255, name: 'Minecart (Steampunk)', internalName: 'SteampunkMinecart', type: 'Buff', zh: '矿车' },
  { id: 256, name: 'Minecart (Steampunk Legacy Unused)', internalName: 'SteampunkMinecartLegacyUnused', type: 'Buff' },
  { id: 257, name: 'Lucky', internalName: 'Lucky', type: 'Buff', zh: '幸运' },
  { id: 258, name: "Lil' Harpy", internalName: 'LilHarpy', type: 'Buff', zh: '小鸟妖' },
  { id: 259, name: 'Fennec Fox', internalName: 'FennecFox', type: 'Buff', zh: '耳廓狐' },
  { id: 260, name: 'Glittery Butterfly', internalName: 'GlitteryButterfly', type: 'Buff', zh: '闪光蝴蝶' },
  { id: 261, name: 'Baby Imp', internalName: 'BabyImp', type: 'Buff', zh: '小鬼宝宝' },
  { id: 262, name: 'Baby Red Panda', internalName: 'BabyRedPanda', type: 'Buff', zh: '小熊猫宝宝' },
  { id: 263, name: 'Desert Tiger', internalName: 'StormTiger', type: 'Buff', zh: '沙漠虎' },
  { id: 264, name: 'Plantero', internalName: 'Plantero', type: 'Buff', zh: '微型世纪之花' },
  { id: 265, name: 'Flamingo', internalName: 'Flamingo', type: 'Buff', zh: '火烈鸟' },
  { id: 266, name: 'Dynamite Kitten', internalName: 'DynamiteKitten', type: 'Buff', zh: '雷管小猫' },
  { id: 267, name: 'Baby Werewolf', internalName: 'BabyWerewolf', type: 'Buff', zh: '狼人宝宝' },
  { id: 268, name: 'Shadow Mimic', internalName: 'ShadowMimic', type: 'Buff', zh: '暗影宝箱怪' },
  { id: 269, name: 'Minecart (Coffin)', internalName: 'CoffinMinecart', type: 'Buff', zh: '矿车' },
  { id: 270, name: 'Minecart (Coffin Legacy Unused)', internalName: 'CoffinMinecartLegacyUnused', type: 'Buff' },
  { id: 271, name: 'Enchanted Daggers', internalName: 'Smolstar', type: 'Buff', zh: '附魔飞刀' },
  { id: 272, name: 'Digging Molecart', internalName: 'DiggingMoleMinecart', type: 'Buff', zh: '挖掘鼹鼠矿车' },
  { id: 273, name: 'Digging Molecart Legacy Unused', internalName: 'DiggingMoleMinecartLegacyUnused', type: 'Buff' },
  { id: 274, name: 'Volt Bunny', internalName: 'VoltBunny', type: 'Buff', zh: '伏特兔' },
  { id: 275, name: 'Painted Horse Mount', internalName: 'PaintedHorseMount', type: 'Buff', zh: '花马坐骑' },
  { id: 276, name: 'Majestic Horse Mount', internalName: 'MajesticHorseMount', type: 'Buff', zh: '骏马坐骑' },
  { id: 277, name: 'Dark Horse Mount', internalName: 'DarkHorseMount', type: 'Buff', zh: '黑马坐骑' },
  { id: 278, name: 'Pogo Stick Mount', internalName: 'PogoStickMount', type: 'Buff', zh: '蹦蹦跷坐骑' },
  { id: 279, name: 'Pirate Ship Mount', internalName: 'PirateShipMount', type: 'Buff', zh: '海盗船坐骑' },
  { id: 280, name: 'Tree Mount', internalName: 'SpookyWoodMount', type: 'Buff', zh: '阴森树坐骑' },
  { id: 281, name: 'Santank Mount', internalName: 'SantankMount', type: 'Buff', zh: '圣诞老人坦克坐骑' },
  { id: 282, name: 'Goat Mount', internalName: 'WallOfFleshGoatMount', type: 'Buff', zh: '山羊坐骑' },
  { id: 283, name: 'Book Mount', internalName: 'DarkMageBookMount', type: 'Buff', zh: '书坐骑' },
  { id: 284, name: 'Slime Prince', internalName: 'KingSlimePet', type: 'Buff', zh: '史莱姆王子' },
  { id: 285, name: 'Suspicious Eye', internalName: 'EyeOfCthulhuPet', type: 'Buff', zh: '可疑眼睛' },
  { id: 286, name: 'Eater of Worms', internalName: 'EaterOfWorldsPet', type: 'Buff', zh: '蠕虫吞噬怪' },
  { id: 287, name: 'Spider Brain', internalName: 'BrainOfCthulhuPet', type: 'Buff', zh: '蜘蛛脑' },
  { id: 288, name: 'Skeletron Jr.', internalName: 'SkeletronPet', type: 'Buff', zh: '小骷髅王' },
  { id: 289, name: 'Honey Bee', internalName: 'QueenBeePet', type: 'Buff', zh: '宝贝蜜蜂' },
  { id: 290, name: 'Destroyer-Lite', internalName: 'DestroyerPet', type: 'Buff', zh: '微型毁灭者' },
  { id: 291, name: 'Rez and Spaz', internalName: 'TwinsPet', type: 'Buff', zh: '激光眼和魔焰眼' },
  { id: 292, name: 'Mini Prime', internalName: 'SkeletronPrimePet', type: 'Buff', zh: '小机械骷髅王' },
  { id: 293, name: 'Plantera Seedling', internalName: 'PlanteraPet', type: 'Buff', zh: '世纪之花幼苗' },
  { id: 294, name: 'Toy Golem', internalName: 'GolemPet', type: 'Buff', zh: '玩具石巨人' },
  { id: 295, name: 'Tiny Fishron', internalName: 'DukeFishronPet', type: 'Buff', zh: '小猪龙鱼' },
  { id: 296, name: 'Phantasmal Dragon', internalName: 'LunaticCultistPet', type: 'Buff', zh: '小幻影龙' },
  { id: 297, name: 'Moonling', internalName: 'MoonLordPet', type: 'Buff', zh: '月精灵' },
  { id: 298, name: 'Fairy Princess', internalName: 'FairyQueenPet', type: 'Buff', zh: '仙灵公主' },
  { id: 299, name: "Jack 'O Lantern", internalName: 'PumpkingPet', type: 'Buff', zh: '杰克南瓜灯' },
  { id: 300, name: 'Everscream Sapling', internalName: 'EverscreamPet', type: 'Buff', zh: '常绿尖叫怪树苗' },
  { id: 301, name: 'Ice Queen', internalName: 'IceQueenPet', type: 'Buff', zh: '冰雪女王' },
  { id: 302, name: 'Alien Skater', internalName: 'MartianPet', type: 'Buff', zh: '异星滑板小子' },
  { id: 303, name: 'Baby Ogre', internalName: 'DD2OgrePet', type: 'Buff', zh: '食人魔宝宝' },
  { id: 304, name: 'Itsy Betsy', internalName: 'DD2BetsyPet', type: 'Buff', zh: '小双足翼龙' },
  { id: 305, name: 'Lava Shark Mount', internalName: 'LavaSharkMount', type: 'Buff', zh: '熔岩鲨坐骑' },
  { id: 306, name: 'Titanium Barrier', internalName: 'TitaniumStorm', type: 'Buff', zh: '钛金屏障' },
  { id: 307, name: 'Bland Whip Enemy Debuff', internalName: 'BlandWhipEnemyDebuff', type: 'Debuff' },
  { id: 308, name: "Durendal's Blessing", internalName: 'SwordWhipPlayerBuff', type: 'Buff', zh: '迪朗达尔祝福' },
  { id: 309, name: 'Sword Whip NPC Debuff', internalName: 'SwordWhipNPCDebuff', type: 'Debuff' },
  { id: 310, name: 'Scythe Whip Enemy Debuff', internalName: 'ScytheWhipEnemyDebuff', type: 'Debuff' },
  { id: 311, name: 'Harvest Time', internalName: 'ScytheWhipPlayerBuff', type: 'Buff', zh: '收割时刻' },
  { id: 312, name: 'A Nice Buff', internalName: 'CoolWhipPlayerBuff', type: 'Buff', zh: '一种不错的增益' },
  { id: 313, name: 'Flame Whip Enemy Debuff', internalName: 'FlameWhipEnemyDebuff', type: 'Debuff' },
  { id: 314, name: "Jungle's Fury", internalName: 'ThornWhipPlayerBuff', type: 'Buff', zh: '丛林之怒' },
  { id: 315, name: 'Thorn Whip NPC Debuff', internalName: 'ThornWhipNPCDebuff', type: 'Debuff' },
  { id: 316, name: 'Rainbow Whip NPC Debuff', internalName: 'RainbowWhipNPCDebuff', type: 'Debuff' },
  { id: 317, name: 'Slime Princess', internalName: 'QueenSlimePet', type: 'Buff', zh: '史莱姆公主' },
  { id: 318, name: 'Winged Slime Mount', internalName: 'QueenSlimeMount', type: 'Buff', zh: '羽翼史莱姆坐骑' },
  { id: 319, name: 'Mace Whip NPC Debuff', internalName: 'MaceWhipNPCDebuff', type: 'Debuff' },
  { id: 320, name: 'Sparkle Slime', internalName: 'GelBalloonBuff', type: 'Debuff', zh: '闪耀史莱姆' },
  { id: 321, name: 'Cerebral Mindtrick', internalName: 'BrainOfConfusionBuff', type: 'Debuff', zh: '控脑术' },
  { id: 322, name: 'Terraprisma', internalName: 'EmpressBlade', type: 'Buff', zh: '泰拉棱镜' },
  { id: 323, name: 'Hellfire', internalName: 'OnFire3', type: 'Debuff', zh: '狱炎' },
  { id: 324, name: 'Frostbite', internalName: 'Frostburn2', type: 'Debuff', zh: '冻伤' },
  { id: 325, name: 'Flinx', internalName: 'FlinxMinion', type: 'Buff', zh: '小雪怪' },
  { id: 326, name: 'Bone Whip NPC Debuff', internalName: 'BoneWhipNPCDebuff', type: 'Debuff' },
  { id: 327, name: 'Bernie', internalName: 'BerniePet', type: 'Buff', zh: '伯尼' },
  { id: 328, name: 'Glommer', internalName: 'GlommerPet', type: 'Buff', zh: '格罗姆' },
  { id: 329, name: 'Tiny Deerclops', internalName: 'DeerclopsPet', type: 'Buff', zh: '小独眼巨鹿' },
  { id: 330, name: 'Pig', internalName: 'PigPet', type: 'Buff', zh: '猪' },
  { id: 331, name: 'Chester', internalName: 'ChesterPet', type: 'Buff', zh: '切斯特' },
  { id: 332, name: 'Peckish', internalName: 'NeutralHunger', type: 'Debuff', zh: '稍饿' },
  { id: 333, name: 'Hungry', internalName: 'Hunger', type: 'Debuff', zh: '饥饿' },
  { id: 334, name: 'Starving', internalName: 'Starving', type: 'Debuff', zh: '极饿' },
  { id: 335, name: 'Abigail', internalName: 'AbigailMinion', type: 'Buff', zh: '阿比盖尔' },
  { id: 336, name: 'Hearty Meal', internalName: 'HeartyMeal', type: 'Buff', zh: '丰盛大餐' },
  { id: 337, name: 'Tentacle Spike', internalName: 'TentacleSpike', type: 'Debuff' },
  { id: 338, name: 'Fart Kart', internalName: 'FartMinecart', type: 'Buff', zh: '臭屁车' },
  { id: 339, name: 'Fart Kart Legacy Unused', internalName: 'FartMinecartLegacyUnused', type: 'Buff' },
  { id: 340, name: 'Cool Whip NPC Debuff', internalName: 'CoolWhipNPCDebuff', type: 'Buff' },
  { id: 341, name: 'Slime Royals', internalName: 'DualSlimePet', type: 'Buff', zh: '皇家史莱姆' },
  { id: 342, name: 'Blessing of the Moon', internalName: 'WolfMount', type: 'Buff', zh: '月亮祝福' },
  { id: 343, name: 'Biome Sight', internalName: 'BiomeSight', type: 'Buff', zh: '生物群系视觉' },
  { id: 344, name: 'Blood Butchered', internalName: 'BloodButcherer', type: 'Debuff', zh: '血腥屠宰' },
  { id: 345, name: 'Junimo', internalName: 'JunimoPet', type: 'Buff', zh: '祝尼魔' },
  { id: 346, name: 'Terra Fart Kart', internalName: 'TerraFartMinecart', type: 'Buff', zh: '泰拉臭屁车' },
  { id: 347, name: 'Terra Fart Kart Legacy Unused', internalName: 'TerraFartMinecartLegacyUnused', type: 'Buff' },
  { id: 348, name: 'Strategist', internalName: 'WarTable', type: 'Buff', zh: '战略家' },
  { id: 349, name: 'Blue Chicken', internalName: 'BlueChickenPet', type: 'Buff', zh: '蓝鸡' },
  { id: 350, name: 'Shadow Candle', internalName: 'ShadowCandle', type: 'Debuff', zh: '暗影蜡烛' },
  { id: 351, name: 'Spiffo', internalName: 'Spiffo', type: 'Buff', zh: 'Spiffo' },
  { id: 352, name: 'Caveling Gardener', internalName: 'CavelingGardener', type: 'Buff', zh: '洞穴园丁' },
  { id: 353, name: 'Shimmering', internalName: 'Shimmer', type: 'Debuff', zh: '微光闪烁' },
  { id: 354, name: 'The Dirtiest Block', internalName: 'DirtiestBlock', type: 'Buff', zh: '最土的块' },
  { id: 355, name: 'Mushroom Boi!', internalName: 'DeadCellsMushroomBoiMinion', type: 'Buff', zh: '蘑菇君！' },
  { id: 356, name: 'Swarm Biter', internalName: 'DeadCellsSwarmBiter', type: 'Buff', zh: '咬咬虫群' },
  { id: 357, name: 'Cob Whip NPC Debuff', internalName: 'CobWhipNPCDebuff', type: 'Debuff' },
  { id: 358, name: 'Corrupt Whip NPC Debuff', internalName: 'CorruptWhipNPCDebuff', type: 'Debuff' },
  { id: 359, name: 'Crimson Whip NPC Debuff', internalName: 'CrimsonWhipNPCDebuff', type: 'Debuff' },
  { id: 360, name: 'Meteor Whip NPC Debuff', internalName: 'MeteorWhipNPCDebuff', type: 'Debuff' },
  { id: 361, name: 'Flower Whip NPC Debuff', internalName: 'FlowerWhipNPCDebuff', type: 'Debuff' },
  { id: 362, name: 'Eel Whip NPC Debuff', internalName: 'EelWhipNPCDebuff', type: 'Debuff' },
  { id: 363, name: 'Constellation Whip NPC Debuff', internalName: 'ConstellationWhipNPCDebuff', type: 'Debuff' },
  { id: 364, name: 'Moon Lord Whip NPC Debuff', internalName: 'MoonLordWhipNPCDebuff', type: 'Debuff' },
  { id: 365, name: 'Whip Spider', internalName: 'CobWhipPlayerBuff', type: 'Buff', zh: '鞭蜘蛛' },
  { id: 366, name: 'Alchemic Enhancement', internalName: 'DeadCellsPotionStation', type: 'Buff', zh: '炼金强化' },
  { id: 367, name: 'Flower Whip NPC Debuff Proc', internalName: 'FlowerWhipNPCDebuffProc', type: 'Debuff' },
  { id: 368, name: 'Moon Lord Whip NPC Debuff Proc', internalName: 'MoonLordWhipNPCDebuffProc', type: 'Debuff' },
  { id: 369, name: 'Meteor Whip NPC Debuff Proc', internalName: 'MeteorWhipNPCDebuffProc', type: 'Debuff' },
  { id: 370, name: 'Instinct of the Raptor', internalName: 'VelociraptorMount', type: 'Buff', zh: '迅猛龙本能' },
  { id: 371, name: 'Pufferfish', internalName: 'Pufferfish', type: 'Buff', zh: '河豚' },
  { id: 372, name: 'Cenaxe', internalName: 'AxeFairyPet', type: 'Buff', zh: '森斧精灵' },
  { id: 373, name: 'Friendly Boulder', internalName: 'BoulderPet', type: 'Buff', zh: '友好巨石' },
  { id: 374, name: 'Nature of the Rat', internalName: 'RatMount', type: 'Buff', zh: '大鼠本性' },
  { id: 375, name: 'Hemorrhage', internalName: 'Hemorrhage', type: 'Debuff', zh: '出血' },
  { id: 376, name: 'Torch Blessing', internalName: 'TorchGodPotion', type: 'Buff', zh: '火把祝福' },
  { id: 377, name: 'Curse of the Bat', internalName: 'BatMount', type: 'Buff', zh: '蝙蝠诅咒' },
  { id: 378, name: 'Blue Roller Skates', internalName: 'RollerSkatesMount', type: 'Buff', zh: '蓝轮滑鞋' },
  { id: 379, name: 'Green Roller Skates', internalName: 'RollerSkatesGreenMount', type: 'Buff', zh: '绿轮滑鞋' },
  { id: 380, name: 'Classic Roller Skates', internalName: 'RollerSkatesWhiteMount', type: 'Buff', zh: '经典轮滑鞋' },
  { id: 381, name: 'Party Roller Skates', internalName: 'RollerSkatesPinkMount', type: 'Buff', zh: '派对轮滑鞋' },
  { id: 382, name: 'Friendly Rainbow Boulder', internalName: 'RainbowBoulderPet', type: 'Buff', zh: '友好彩虹巨石' },
  { id: 383, name: 'High Spirits', internalName: 'Kite', type: 'Buff', zh: '放飞心灵' },
  { id: 384, name: 'Form of the Fae', internalName: 'PixieMount', type: 'Buff', zh: '仙灵形态' },
  { id: 385, name: 'Cattiva', internalName: 'PalworldMinionCattiva', type: 'Buff', zh: '捣蛋猫' },
  { id: 386, name: 'Foxparks', internalName: 'PalworldMinionFoxsparks', type: 'Buff', zh: '火绒狐' },
  { id: 387, name: 'Chillet', internalName: 'PalworldPetChillet', type: 'Buff', zh: '疾旋鼬' },
  { id: 388, name: 'Chillet Ignis', internalName: 'PalworldPetChilletIgnis', type: 'Buff', zh: '桃旋鼬' },
]

export const DEFAULT_ONE_CLICK_BUFF_IDS = [
  1,
  2,
  3,
  5,
  6,
  7,
  8,
  9,
  11,
  12,
  14,
  16,
  17,
  26,
  29,
  87,
  89,
  93,
  104,
  105,
  107,
  108,
  110,
  111,
  112,
  113,
  115,
  116,
  117,
  124,
  146,
  150,
  157,
  158,
  159,
  165,
  215,
  257,
  336,
  343,
  348,
  366,
]

export const POSITIVE_TERRARIA_BUFFS = TERRARIA_BUFFS.filter(buff => buff.type === 'Buff')

export function terrariaBuffDisplayName(buff: TerrariaBuff) {
  return buff.zh ? `${buff.zh} / ${buff.name}` : buff.name
}

export function terrariaBuffLabel(buff: TerrariaBuff) {
  return `#${buff.id} ${terrariaBuffDisplayName(buff)} (${buff.type})`
}

export const TERRARIA_BUFF_OPTIONS = TERRARIA_BUFFS.map(buff => ({
  label: terrariaBuffLabel(buff),
  value: buff.id,
}))

export const POSITIVE_TERRARIA_BUFF_OPTIONS = POSITIVE_TERRARIA_BUFFS.map(buff => ({
  label: terrariaBuffLabel(buff),
  value: buff.id,
}))

export function findTerrariaBuff(id: number) {
  return TERRARIA_BUFFS.find(buff => buff.id === id)
}
