export interface PermissionDescription {
  descriptionEn: string
  descriptionZh?: string
  commands: string
}

export const PERMISSION_DESCRIPTIONS: Record<string, PermissionDescription> = {
  "tshock.account.changepassword": { descriptionEn: "User can change password in game.", commands: "/password" },
  "tshock.account.login": { descriptionEn: "User can login in game.", commands: "/login" },
  "tshock.account.logout": { descriptionEn: "User can logout in game.", commands: "/logout" },
  "tshock.account.register": { descriptionEn: "User can register account in game.", commands: "/register" },
  "tshock.accountinfo.check": { descriptionEn: "Player can check if a username is registered and see its last login time.", commands: "/accountinfo (/ai)" },
  "tshock.accountinfo.details": { descriptionEn: "Player can see advanced information about any user account.", commands: "None" },
  "tshock.admin.antibuild": { descriptionEn: "User can set build protection status.", commands: "/antibuild" },
  "tshock.admin.ban": { descriptionEn: "User can ban others.", commands: "/ban" },
  "tshock.admin.broadcast": { descriptionEn: "User can broadcast messages.", commands: "/broadcast (/bc /say)" },
  "tshock.admin.group": { descriptionEn: "User can manage groups.", commands: "/group" },
  "tshock.admin.itemban": { descriptionEn: "User can manage item bans.", commands: "/itemban" },
  "tshock.admin.kick": { descriptionEn: "User can kick others.", commands: "/kick" },
  "tshock.admin.mute": { descriptionEn: "User can mute and unmute users.", commands: "/mute (/unmute)" },
  "tshock.admin.noban": { descriptionEn: "Prevents you from being banned.", commands: "None" },
  "tshock.admin.nokick": { descriptionEn: "Prevents you from being kicked.", commands: "None" },
  "tshock.admin.projectileban": { descriptionEn: "User can manage projectile bans.", commands: "/projban" },
  "tshock.admin.region": { descriptionEn: "User can manage regions.", commands: "/region" },
  "tshock.admin.savessi": { descriptionEn: "User can save all the players SSI (server side character) state.", commands: "/overridessc (/ossc), /savessc" },
  "tshock.admin.seeplayerids": { descriptionEn: "User can see the id of players with /who.", commands: "None" },
  "tshock.admin.tempgroup": { descriptionEn: "User can elevate other users' groups temporarily.", commands: "/tempgroup" },
  "tshock.admin.tileban": { descriptionEn: "User can manage tile bans.", commands: "/tileban" },
  "tshock.admin.userinfo": { descriptionEn: "User can get other users' info.", commands: "/userinfo (/ui)" },
  "tshock.admin.viewlogs": { descriptionEn: "Specific log messages are sent to users with this permission.", commands: "/displaylogs" },
  "tshock.admin.warp": { descriptionEn: "User can manage warps.", commands: "None" },
  "tshock.annoy": { descriptionEn: "User can annoy others.", commands: "/annoy, /rocket, /firework" },
  "tshock.buff.others": { descriptionEn: "User can buff other players.", commands: "/gbuff (/buffplayer)" },
  "tshock.buff.self": { descriptionEn: "User can buff self.", commands: "/buff" },
  "tshock.canchat": { descriptionEn: "Player can chat.", commands: "None" },
  "tshock.cfg.createdumps": { descriptionEn: "User can create reference files of Terraria IDs and the permission matrix in the server folder.", commands: "/dump-reference-data" },
  "tshock.cfg.maintenance": { descriptionEn: "User is notified when an update is available, user can turn off / restart the server.", commands: "/checkupdates, /off (/exit /stop), /off-nosave (/exit-nosave /stop-nosave), /version" },
  "tshock.cfg.password": { descriptionEn: "User can edit the server password.", commands: "/serverpassword" },
  "tshock.cfg.reload": { descriptionEn: "User can reload the configurations file.", commands: "/reload" },
  "tshock.cfg.whitelist": { descriptionEn: "User can modify the whitelist.", commands: "/whitelist" },
  "tshock.clear": { descriptionEn: "User can clear items or projectiles.", commands: "/clear" },
  "tshock.godmode": { descriptionEn: "Player recovers health as damage is taken.  Can be one shotted.", commands: "/godmode (/god)" },
  "tshock.godmode.other": { descriptionEn: "User can godmode other players.", commands: "None" },
  "tshock.heal": { descriptionEn: "User can heal players.", commands: "/heal" },
  "tshock.ignore.damage": { descriptionEn: "Prevents your actions from being ignored if damage is too high.", commands: "None" },
  "tshock.ignore.dropbanneditem": { descriptionEn: "Allow dropping banned items without the item being eaten.", commands: "None" },
  "tshock.ignore.hp": { descriptionEn: "Prevents you from being disabled by abnormal HP.", commands: "None" },
  "tshock.ignore.itemstack": { descriptionEn: "Prevents you from being disabled by stack hack detection.", commands: "None" },
  "tshock.ignore.liquid": { descriptionEn: "Prevents you from being disabled by liquid set abuse detection.", commands: "None" },
  "tshock.ignore.mp": { descriptionEn: "Prevents you from being disabled by abnormal MP.", commands: "None" },
  "tshock.ignore.npcbuff": { descriptionEn: "Prevents your from being kicked by npc buff hack detection.", commands: "None" },
  "tshock.ignore.paint": { descriptionEn: "Prevents you from being disabled by paint abuse detection.", commands: "None" },
  "tshock.ignore.placetile": { descriptionEn: "Prevents you from being reverted by place tile abuse detection.", commands: "None" },
  "tshock.ignore.projectile": { descriptionEn: "Prevents you from being disabled by projectile abuse detection.", commands: "None" },
  "tshock.ignore.removetile": { descriptionEn: "Prevents you from being reverted by kill tile abuse detection.", commands: "None" },
  "tshock.ignore.sendtilesquare": { descriptionEn: "Allow unrestricted SendTileSquare usage, for client side world editing.", commands: "None" },
  "tshock.ignore.ssc": { descriptionEn: "Bypass server side character checks.", commands: "None" },
  "tshock.info": { descriptionEn: "User can get the server info.", commands: "/serverinfo" },
  "tshock.item.give": { descriptionEn: "User can give items.", commands: "/give (/g)" },
  "tshock.item.spawn": { descriptionEn: "User can spawn items.", commands: "/item (/i)" },
  "tshock.item.usebanned": { descriptionEn: "Allows you to use banned items.", commands: "None" },
  "tshock.journey.biomespreadfreeze": { descriptionEn: "User can use Creative UI to stop the biome spread of the world.", commands: "None" },
  "tshock.journey.godmode": { descriptionEn: "User can use Creative UI to toggle character godmode.", commands: "None" },
  "tshock.journey.placementrange": { descriptionEn: "User can use Creative UI to toggle increased placement range.", commands: "None" },
  "tshock.journey.rain.freeze": { descriptionEn: "User can use Creative UI to stop the world rain strength from changing.", commands: "None" },
  "tshock.journey.rain.strength": { descriptionEn: "User can use Creative UI to set world rain strength/seed.", commands: "None" },
  "tshock.journey.research": { descriptionEn: "User can contribute research by sacrificing items", commands: "None" },
  "tshock.journey.setdifficulty": { descriptionEn: "User can use Creative UI to set world difficulty/mode.", commands: "None" },
  "tshock.journey.setspawnrate": { descriptionEn: "User can use Creative UI to set the NPC spawn rate of the world.", commands: "None" },
  "tshock.journey.time.freeze": { descriptionEn: "User can use Creative UI free", commands: "" },
  "tshock.journey.time.set": { descriptionEn: "User can use Creative UI to set world time.", commands: "None" },
  "tshock.journey.time.setspeed": { descriptionEn: "User can use Creative UI to set world time speed.", commands: "None" },
  "tshock.journey.wind.freeze": { descriptionEn: "User can use Creative UI to stop the world wind strength from changing.", commands: "None" },
  "tshock.journey.wind.strength": { descriptionEn: "User can use Creative UI to set world wind strength/seed.", commands: "None" },
  "tshock.kill": { descriptionEn: "User can kill others.", commands: "/kill (/slay)" },
  "tshock.npc.butcher": { descriptionEn: "User can kill all enemy npcs.", commands: "/butcher" },
  "tshock.npc.clearanglerquests": { descriptionEn: "User can clear the list of users who have completed an angler quest that day.", commands: "/clearangler" },
  "tshock.npc.hurttown": { descriptionEn: "User can hurt town NPCs.", commands: "None" },
  "tshock.npc.invade": { descriptionEn: "User can start an invasion. Warning: high network use. Easy to abuse.", commands: "None" },
  "tshock.npc.maxspawns": { descriptionEn: "User can edit the max spawns.", commands: "/maxspawns" },
  "tshock.npc.rename": { descriptionEn: "User can rename NPCs.", commands: "/renamenpc" },
  "tshock.npc.spawnboss": { descriptionEn: "User can spawn bosses.", commands: "/spawnboss (/sb)" },
  "tshock.npc.spawnmob": { descriptionEn: "User can spawn npcs.", commands: "/spawnmob (/sm)" },
  "tshock.npc.spawnpets": { descriptionEn: "User can spawn pets. Warning: high network use. Easy to abuse.", commands: "None" },
  "tshock.npc.spawnrate": { descriptionEn: "User can edit the spawnrate.", commands: "/spawnrate" },
  "tshock.npc.startdd2": { descriptionEn: "User can start the dd2 event.", commands: "None" },
  "tshock.npc.startinvasion": { descriptionEn: "User can start invasions (Goblin/Snow Legion) using items.", commands: "None" },
  "tshock.npc.summonboss": { descriptionEn: "User can summon bosses using items.", commands: "None" },
  "tshock.partychat": { descriptionEn: "User can use party chat in game.", commands: "/party (/p)" },
  "tshock.projectiles.usebanned": { descriptionEn: "Player can use banned projectiles.", commands: "None" },
  "tshock.reservedslot": { descriptionEn: "Allows you to bypass the max slots for up to 5 slots above your max.", commands: "None" },
  "tshock.respawn": { descriptionEn: "Player can respawn themselves.", commands: "/respawn" },
  "tshock.respawn.other": { descriptionEn: "Player can respawn others.", commands: "None" },
  "tshock.sendemoji": { descriptionEn: "Player can send emotes.", commands: "None" },
  "tshock.slap": { descriptionEn: "User can slap others.", commands: "/slap" },
  "tshock.ssc.upload": { descriptionEn: "User can upload their joined character data as SSC data.", commands: "/uploadssc" },
  "tshock.ssc.upload.others": { descriptionEn: "User can upload other players join data to the SSC database.", commands: "None" },
  "tshock.su": { descriptionEn: "Allows a user to elevate to superadmin for 10 minutes.", commands: "/su, /sudo" },
  "tshock.superadmin.user": { descriptionEn: "Meant for super admins only.", commands: "/user" },
  "tshock.synclocalarea": { descriptionEn: "Player can resync themselves with server state.", commands: "/sync" },
  "tshock.thirdperson": { descriptionEn: "User can talk in third person.", commands: "/me" },
  "tshock.tiles.usebanned": { descriptionEn: "Player can place banned tiles.", commands: "None" },
  "tshock.tp.allothers": { descriptionEn: "User can teleport *everyone* to them.", commands: "None" },
  "tshock.tp.block": { descriptionEn: "Users can stop people from teleporting.", commands: "/tpallow" },
  "tshock.tp.demonconch": { descriptionEn: "User can use the Demon Conch.", commands: "None" },
  "tshock.tp.getpos": { descriptionEn: "User can get the position of players.", commands: "/pos" },
  "tshock.tp.home": { descriptionEn: "User can use /home.", commands: "/home" },
  "tshock.tp.magicconch": { descriptionEn: "User can use the Magic Conch.", commands: "None" },
  "tshock.tp.npc": { descriptionEn: "User can teleport to an NPC.", commands: "/tpnpc" },
  "tshock.tp.others": { descriptionEn: "User can teleport other people.", commands: "/tphere" },
  "tshock.tp.override": { descriptionEn: "Users can override teleport blocks.", commands: "None" },
  "tshock.tp.pos": { descriptionEn: "User can teleport to tile positions.", commands: "/tppos" },
  "tshock.tp.pylon": { descriptionEn: "User can use pylons to teleport", commands: "None" },
  "tshock.tp.rod": { descriptionEn: "User can use the Rod of Discord.", commands: "None" },
  "tshock.tp.self": { descriptionEn: "User can teleport to others.", commands: "/tp" },
  "tshock.tp.silent": { descriptionEn: "Users can teleport to people without showing a notice", commands: "None" },
  "tshock.tp.spawn": { descriptionEn: "User can use /spawn.", commands: "/spawn" },
  "tshock.tp.tppotion": { descriptionEn: "User can use Teleportation Potions.", commands: "None" },
  "tshock.tp.wormhole": { descriptionEn: "User can use wormhole potions.", commands: "None" },
  "tshock.warp": { descriptionEn: "User can use warps.", commands: "/warp" },
  "tshock.whisper": { descriptionEn: "User can whisper to others.", commands: "/reply (/r), /whisper (/w /tell /pm /dm), /wallow (/wa)" },
  "tshock.world.converthardmode": { descriptionEn: "User can convert hallow into corruption and vice-versa.", commands: "None" },
  "tshock.world.editregion": { descriptionEn: "Allows you to edit regions.", commands: "None" },
  "tshock.world.editspawn": { descriptionEn: "Allows you to edit the spawn.", commands: "/protectspawn" },
  "tshock.world.events": { descriptionEn: "User can use the 'worldevent' command", commands: "/worldevent" },
  "tshock.world.events.bloodmoon": { descriptionEn: "User can use the 'bloodmoon' subcommand of the 'worldevent' command", commands: "None" },
  "tshock.world.events.eclipse": { descriptionEn: "User can use the 'eclipse' subcommand of the 'worldevent' command", commands: "None" },
  "tshock.world.events.fullmoon": { descriptionEn: "User can use the 'fullmoon' subcommand of the 'worldevent' command", commands: "None" },
  "tshock.world.events.invasion": { descriptionEn: "User can use the 'invasion' subcommand of the 'worldevent' command", commands: "None" },
  "tshock.world.events.lanternsnight": { descriptionEn: "User can use the 'lanternsnight' subcommand of the 'worldevent' command", commands: "None" },
  "tshock.world.events.meteor": { descriptionEn: "User can use the 'meteor' subcommand of the 'worldevent' command", commands: "None" },
  "tshock.world.events.rain": { descriptionEn: "User can use the 'rain' subcommand of the 'worldevent' command", commands: "None" },
  "tshock.world.events.sandstorm": { descriptionEn: "User can use the 'sandstorm' subcommand of the 'worldevent' command", commands: "None" },
  "tshock.world.grow": { descriptionEn: "User can grow plants.", commands: "/grow" },
  "tshock.world.growevil": { descriptionEn: "User can grow evil biome plants.", commands: "None" },
  "tshock.world.hardmode": { descriptionEn: "User can change hardmode state.", commands: "/hardmode" },
  "tshock.world.info": { descriptionEn: "User can get the world info.", commands: "/worldinfo" },
  "tshock.world.modify": { descriptionEn: "User can modify the world.", commands: "None" },
  "tshock.world.movenpc": { descriptionEn: "User can change the homes of NPCs.", commands: "None" },
  "tshock.world.paint": { descriptionEn: "User can paint tiles.", commands: "None" },
  "tshock.world.rain": { descriptionEn: "User can turn on or off the rain.", commands: "None" },
  "tshock.world.sandstorm": { descriptionEn: "User can turn on or off sandstorms.", commands: "None" },
  "tshock.world.save": { descriptionEn: "User can save the world.", commands: "/save" },
  "tshock.world.setdungeon": { descriptionEn: "User can set the dungeon's location.", commands: "/setdungeon" },
  "tshock.world.sethalloween": { descriptionEn: "User can force the server to Halloween mode.", commands: "/forcehalloween" },
  "tshock.world.setspawn": { descriptionEn: "User can set the world spawn.", commands: "/setspawn" },
  "tshock.world.settleliquids": { descriptionEn: "User can settle liquids.", commands: "/settle" },
  "tshock.world.time.bloodmoon": { descriptionEn: "User can force a blood moon.", commands: "None" },
  "tshock.world.time.dropmeteor": { descriptionEn: "User can drop a meteor.", commands: "None" },
  "tshock.world.time.eclipse": { descriptionEn: "User can force an eclipse.", commands: "None" },
  "tshock.world.time.fullmoon": { descriptionEn: "User can force a full moon.", commands: "None" },
  "tshock.world.time.set": { descriptionEn: "User can set the time.", commands: "/time" },
  "tshock.world.time.usesundial": { descriptionEn: "Player can use the Enchanted Sundial item.", commands: "None" },
  "tshock.world.toggleexpert": { descriptionEn: "User can change expert state.", commands: "/worldmode (/gamemode)" },
  "tshock.world.toggleparty": { descriptionEn: "Player can toggle party event.", commands: "None" },
  "tshock.world.wind": { descriptionEn: "User can modify the wind.", commands: "/wind" },
}

export const PERMISSION_DESCRIPTIONS_ZH: Record<string, string> = {
  "tshock.account.changepassword": "允许玩家在游戏内修改自己的 TShock 账号密码。",
  "tshock.account.login": "允许玩家在游戏内登录 TShock 账号。",
  "tshock.account.logout": "允许玩家在游戏内退出登录。",
  "tshock.account.register": "允许玩家在游戏内注册 TShock 账号。",
  "tshock.accountinfo.check": "允许检查某个用户名是否已注册，并查看最后登录时间。",
  "tshock.accountinfo.details": "允许查看任意用户账号的高级信息。",
  "tshock.admin.antibuild": "允许设置服务器建造保护状态。",
  "tshock.admin.ban": "允许封禁玩家。",
  "tshock.admin.broadcast": "允许发送全服广播消息。",
  "tshock.admin.group": "允许管理 TShock 用户组。",
  "tshock.admin.itemban": "允许管理物品封禁。",
  "tshock.admin.kick": "允许踢出玩家。",
  "tshock.admin.mute": "允许禁言和解除玩家禁言。",
  "tshock.admin.noban": "防止自己被封禁。",
  "tshock.admin.nokick": "防止自己被踢出。",
  "tshock.admin.projectileban": "允许管理弹幕/射弹封禁。",
  "tshock.admin.region": "允许管理区域。",
  "tshock.admin.savessi": "允许保存所有玩家的服务端角色数据（SSC/SSI）。",
  "tshock.admin.seeplayerids": "允许通过 /who 查看玩家 ID。",
  "tshock.admin.tempgroup": "允许临时提升或修改其他玩家的用户组。",
  "tshock.admin.tileban": "允许管理方块封禁。",
  "tshock.admin.userinfo": "允许查看其他用户的信息。",
  "tshock.admin.viewlogs": "允许接收和查看特定日志消息。",
  "tshock.admin.warp": "允许管理传送点。",
  "tshock.annoy": "允许使用骚扰类命令影响其他玩家。",
  "tshock.buff.others": "允许给其他玩家施加 Buff。",
  "tshock.buff.self": "允许给自己施加 Buff。",
  "tshock.canchat": "允许玩家聊天。",
  "tshock.cfg.createdumps": "允许在服务器目录生成 Terraria ID 和权限矩阵参考文件。",
  "tshock.cfg.maintenance": "允许接收更新通知，并关闭或重启服务器。",
  "tshock.cfg.password": "允许修改服务器进入密码。",
  "tshock.cfg.reload": "允许重载配置文件。",
  "tshock.cfg.whitelist": "允许修改白名单。",
  "tshock.clear": "允许清除地面物品或弹幕。",
  "tshock.godmode": "允许开启上帝模式；受伤时恢复生命，但仍可能被秒杀。",
  "tshock.godmode.other": "允许给其他玩家切换上帝模式。",
  "tshock.heal": "允许治疗玩家。",
  "tshock.ignore.damage": "绕过过高伤害检测，防止相关操作被忽略。",
  "tshock.ignore.dropbanneditem": "允许丢弃被封禁物品，且不会被服务器吞掉。",
  "tshock.ignore.hp": "绕过异常生命值检测，防止被禁用操作。",
  "tshock.ignore.itemstack": "绕过物品堆叠异常检测。",
  "tshock.ignore.liquid": "绕过液体放置/修改滥用检测。",
  "tshock.ignore.mp": "绕过异常魔力值检测。",
  "tshock.ignore.npcbuff": "绕过 NPC Buff 作弊检测，防止因此被踢出。",
  "tshock.ignore.paint": "绕过喷漆滥用检测。",
  "tshock.ignore.placetile": "绕过放置方块滥用检测。",
  "tshock.ignore.projectile": "绕过弹幕/射弹滥用检测。",
  "tshock.ignore.removetile": "绕过拆除方块滥用检测。",
  "tshock.ignore.sendtilesquare": "允许不受限制地使用 SendTileSquare，常用于客户端侧世界编辑。",
  "tshock.ignore.ssc": "绕过服务端角色（SSC）检查。",
  "tshock.info": "允许查看服务器信息。",
  "tshock.item.give": "允许给玩家发放物品。",
  "tshock.item.spawn": "允许生成物品。",
  "tshock.item.usebanned": "允许使用被封禁的物品。",
  "tshock.journey.biomespreadfreeze": "允许在旅途模式创意菜单中冻结生物群落蔓延。",
  "tshock.journey.godmode": "允许在旅途模式创意菜单中切换角色上帝模式。",
  "tshock.journey.placementrange": "允许在旅途模式创意菜单中切换增强放置范围。",
  "tshock.journey.rain.freeze": "允许在旅途模式创意菜单中冻结降雨强度变化。",
  "tshock.journey.rain.strength": "允许在旅途模式创意菜单中设置降雨强度/随机种子。",
  "tshock.journey.research": "允许通过牺牲物品贡献研究进度。",
  "tshock.journey.setdifficulty": "允许在旅途模式创意菜单中设置世界难度/模式。",
  "tshock.journey.setspawnrate": "允许在旅途模式创意菜单中设置 NPC 生成率。",
  "tshock.journey.time.freeze": "允许在旅途模式创意菜单中冻结世界时间。",
  "tshock.journey.time.set": "允许在旅途模式创意菜单中设置世界时间。",
  "tshock.journey.time.setspeed": "允许在旅途模式创意菜单中设置时间流速。",
  "tshock.journey.wind.freeze": "允许在旅途模式创意菜单中冻结风力变化。",
  "tshock.journey.wind.strength": "允许在旅途模式创意菜单中设置风力强度/随机种子。",
  "tshock.kill": "允许击杀其他玩家。",
  "tshock.npc.butcher": "允许清除所有敌对 NPC。",
  "tshock.npc.clearanglerquests": "允许清除当天已完成渔夫任务的用户列表。",
  "tshock.npc.hurttown": "允许伤害城镇 NPC。",
  "tshock.npc.invade": "允许发起入侵事件。该能力网络开销较高，容易被滥用。",
  "tshock.npc.maxspawns": "允许修改最大 NPC 生成数量。",
  "tshock.npc.rename": "允许重命名 NPC。",
  "tshock.npc.spawnboss": "允许通过命令生成 Boss。",
  "tshock.npc.spawnmob": "允许通过命令生成 NPC。",
  "tshock.npc.spawnpets": "允许生成宠物。该能力网络开销较高，容易被滥用。",
  "tshock.npc.spawnrate": "允许修改 NPC 生成速率。",
  "tshock.npc.startdd2": "允许启动撒旦军队事件。",
  "tshock.npc.startinvasion": "允许使用物品触发哥布林/雪人军团等入侵。",
  "tshock.npc.summonboss": "允许使用召唤物或正常游戏机制召唤 Boss，例如肉山。",
  "tshock.partychat": "允许使用队伍聊天。",
  "tshock.projectiles.usebanned": "允许使用被封禁的弹幕/射弹。",
  "tshock.reservedslot": "允许在服务器满员时绕过人数上限，最多额外占用 5 个保留位。",
  "tshock.respawn": "允许让自己复活。",
  "tshock.respawn.other": "允许让其他玩家复活。",
  "tshock.sendemoji": "允许发送表情。",
  "tshock.slap": "允许拍打其他玩家。",
  "tshock.ssc.upload": "允许把当前加入服务器的角色数据上传为 SSC 数据。",
  "tshock.ssc.upload.others": "允许把其他玩家加入服务器时的角色数据上传到 SSC 数据库。",
  "tshock.su": "允许临时提升为 superadmin，持续 10 分钟。",
  "tshock.superadmin.user": "仅供 superadmin 使用的用户管理权限。",
  "tshock.synclocalarea": "允许玩家重新同步自己附近区域的服务器状态。",
  "tshock.thirdperson": "允许使用第三人称说话。",
  "tshock.tiles.usebanned": "允许放置被封禁的方块。",
  "tshock.tp.allothers": "允许把所有玩家传送到自己身边。",
  "tshock.tp.block": "允许阻止别人传送到自己。",
  "tshock.tp.demonconch": "允许使用恶魔海螺。",
  "tshock.tp.getpos": "允许获取玩家坐标位置。",
  "tshock.tp.home": "允许使用 /home。",
  "tshock.tp.magicconch": "允许使用魔法海螺。",
  "tshock.tp.npc": "允许传送到 NPC。",
  "tshock.tp.others": "允许传送其他玩家到自己身边。",
  "tshock.tp.override": "允许无视玩家的传送阻止设置。",
  "tshock.tp.pos": "允许传送到指定地图坐标。",
  "tshock.tp.pylon": "允许使用晶塔传送。",
  "tshock.tp.rod": "允许使用混沌传送杖。",
  "tshock.tp.self": "允许传送到其他玩家身边。",
  "tshock.tp.silent": "允许静默传送，不向其他人显示提示。",
  "tshock.tp.spawn": "允许使用 /spawn 回出生点。",
  "tshock.tp.tppotion": "允许使用传送药水。",
  "tshock.tp.wormhole": "允许使用虫洞药水。",
  "tshock.warp": "允许使用传送点。",
  "tshock.whisper": "允许私聊其他玩家。",
  "tshock.world.converthardmode": "允许在神圣与腐化之间转换世界状态。",
  "tshock.world.editregion": "允许编辑区域。",
  "tshock.world.editspawn": "允许编辑出生点保护区域。",
  "tshock.world.events": "允许使用 /worldevent 世界事件命令。",
  "tshock.world.events.bloodmoon": "允许使用 /worldevent bloodmoon 子命令切换血月。",
  "tshock.world.events.eclipse": "允许使用 /worldevent eclipse 子命令切换日食。",
  "tshock.world.events.fullmoon": "允许使用 /worldevent fullmoon 子命令切换满月。",
  "tshock.world.events.invasion": "允许使用 /worldevent invasion 子命令触发入侵。",
  "tshock.world.events.lanternsnight": "允许使用 /worldevent lanternsnight 子命令触发灯笼夜。",
  "tshock.world.events.meteor": "允许使用 /worldevent meteor 子命令掉落陨石。",
  "tshock.world.events.rain": "允许使用 /worldevent rain 子命令切换降雨。",
  "tshock.world.events.sandstorm": "允许使用 /worldevent sandstorm 子命令切换沙尘暴。",
  "tshock.world.grow": "允许催生植物。",
  "tshock.world.growevil": "允许催生邪恶生物群落植物。",
  "tshock.world.hardmode": "允许切换困难模式状态。",
  "tshock.world.info": "允许查看世界信息。",
  "tshock.world.modify": "允许修改世界。",
  "tshock.world.movenpc": "允许修改 NPC 房屋归属。",
  "tshock.world.paint": "允许给方块喷漆。",
  "tshock.world.rain": "允许开启或关闭降雨。",
  "tshock.world.sandstorm": "允许开启或关闭沙尘暴。",
  "tshock.world.save": "允许保存世界。",
  "tshock.world.setdungeon": "允许设置地牢位置。",
  "tshock.world.sethalloween": "允许强制服务器进入万圣节模式。",
  "tshock.world.setspawn": "允许设置世界出生点。",
  "tshock.world.settleliquids": "允许稳定/结算液体。",
  "tshock.world.time.bloodmoon": "允许强制触发血月。",
  "tshock.world.time.dropmeteor": "允许掉落陨石。",
  "tshock.world.time.eclipse": "允许强制触发日食。",
  "tshock.world.time.fullmoon": "允许强制满月。",
  "tshock.world.time.set": "允许设置世界时间。",
  "tshock.world.time.usesundial": "允许使用附魔日晷。",
  "tshock.world.toggleexpert": "允许切换专家/世界模式。",
  "tshock.world.toggleparty": "允许切换派对事件。",
  "tshock.world.wind": "允许修改风力。",
}

for (const [key, descriptionZh] of Object.entries(PERMISSION_DESCRIPTIONS_ZH)) {
  if (PERMISSION_DESCRIPTIONS[key]) {
    PERMISSION_DESCRIPTIONS[key].descriptionZh = descriptionZh
  }
}
