export type TShockCommandCategory =
  | 'info'
  | 'moderation'
  | 'users'
  | 'groups'
  | 'bans'
  | 'world'
  | 'items'
  | 'fun'
  | 'teleport'
  | 'config'
  | 'vanilla'

export type TShockCommandExecution = 'rest' | 'rawcmd' | 'in_game'
export type TShockCommandRisk = 'low' | 'medium' | 'high' | 'danger'
export type TShockParamType =
  | 'player'
  | 'group'
  | 'permission'
  | 'item'
  | 'buff'
  | 'text'
  | 'number'
  | 'boolean'
  | 'select'
  | 'time'
  | 'duration'

export interface TShockCommandParamOption {
  label: string
  value: string | number
}

export interface TShockCommandParam {
  key: string
  label: string
  type: TShockParamType
  required?: boolean
  placeholder?: string
  default?: string | number | boolean
  min?: number
  max?: number
  options?: TShockCommandParamOption[]
  quote?: boolean
}

export interface TShockCommandDefinition {
  id: string
  title: string
  command: string
  aliases?: string[]
  category: TShockCommandCategory
  permission?: string
  restPermission?: string
  execution: TShockCommandExecution
  allowServer: boolean
  risk: TShockCommandRisk
  description: string
  params?: TShockCommandParam[]
  rawTemplate?: string
  action?:
    | 'broadcast'
    | 'serverReload'
    | 'serverRestart'
    | 'serverOff'
    | 'playerKick'
    | 'playerBan'
    | 'playerKill'
    | 'playerMute'
    | 'playerUnmute'
    | 'userCreate'
    | 'userUpdate'
    | 'userDestroy'
    | 'groupCreate'
    | 'groupUpdate'
    | 'groupDestroy'
    | 'banCreate'
    | 'banDestroy'
    | 'worldSave'
    | 'worldButcher'
    | 'worldBloodmoon'
    | 'worldMeteor'
    | 'worldAutosave'
    | 'itemGive'
    | 'rawcmd'
  examples?: string[]
  disabledReason?: string
}

export const TSHOCK_COMMAND_CATEGORY_LABELS: Record<TShockCommandCategory, string> = {
  info: '信息查询',
  moderation: '玩家管理',
  users: '账号管理',
  groups: '用户组',
  bans: '封禁',
  world: '世界管理',
  items: '物品/Buff',
  fun: '趣味/状态',
  teleport: '传送',
  config: '配置维护',
  vanilla: '原版控制台',
}

export const TSHOCK_COMMAND_RISK_LABELS: Record<TShockCommandRisk, string> = {
  low: '低风险',
  medium: '中风险',
  high: '高风险',
  danger: '危险',
}

export const TSHOCK_COMMAND_EXECUTION_LABELS: Record<TShockCommandExecution, string> = {
  rest: 'REST 专用接口',
  rawcmd: 'REST rawcmd',
  in_game: '仅游戏内',
}

const playerParam = (key = 'player', label = '目标玩家'): TShockCommandParam => ({
  key,
  label,
  type: 'player',
  required: true,
})

const reasonParam: TShockCommandParam = {
  key: 'reason',
  label: '原因',
  type: 'text',
  placeholder: '可选',
}

const inGameOnly = 'TShock 源码标记为 AllowServer=false，需要真实游戏内玩家上下文，面板不会发送。'

export const TSHOCK_COMMAND_CATALOG: TShockCommandDefinition[] = [
  {
    id: 'server-status',
    title: '服务器状态',
    command: '/serverinfo',
    category: 'info',
    permission: 'tshock.info',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'low',
    description: '输出服务器运行信息。',
    rawTemplate: '/serverinfo',
    action: 'rawcmd',
    examples: ['/serverinfo'],
  },
  {
    id: 'who',
    title: '在线玩家',
    command: '/who',
    aliases: ['/playing', '/online'],
    category: 'info',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'low',
    description: '列出当前在线玩家。',
    rawTemplate: '/who',
    action: 'rawcmd',
    examples: ['/who'],
  },
  {
    id: 'motd',
    title: '查看 MOTD',
    command: '/motd',
    category: 'info',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'low',
    description: '显示服务器 MOTD。',
    rawTemplate: '/motd',
    action: 'rawcmd',
  },
  {
    id: 'rules',
    title: '查看规则',
    command: '/rules',
    category: 'info',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'low',
    description: '显示服务器规则。',
    rawTemplate: '/rules',
    action: 'rawcmd',
  },
  {
    id: 'broadcast',
    title: '全服广播',
    command: '/broadcast',
    aliases: ['/bc', '/say'],
    category: 'moderation',
    permission: 'tshock.admin.broadcast',
    execution: 'rest',
    allowServer: true,
    risk: 'medium',
    description: '向所有玩家发送广播。',
    params: [{ key: 'message', label: '广播内容', type: 'text', required: true }],
    action: 'broadcast',
    examples: ['/broadcast Server restarting in 5 minutes'],
  },
  {
    id: 'kick',
    title: '踢出玩家',
    command: '/kick',
    category: 'moderation',
    permission: 'tshock.admin.kick',
    restPermission: 'tshock.rest.kick',
    execution: 'rest',
    allowServer: true,
    risk: 'medium',
    description: '将在线玩家踢出服务器。',
    params: [playerParam(), reasonParam],
    action: 'playerKick',
  },
  {
    id: 'player-ban',
    title: '封禁在线玩家',
    command: '/ban',
    category: 'moderation',
    permission: 'tshock.admin.ban',
    restPermission: 'tshock.rest.ban',
    execution: 'rest',
    allowServer: true,
    risk: 'high',
    description: '封禁一个当前在线玩家。',
    params: [playerParam(), reasonParam],
    action: 'playerBan',
  },
  {
    id: 'kill',
    title: '击杀玩家',
    command: '/kill',
    aliases: ['/slay'],
    category: 'moderation',
    permission: 'tshock.kill',
    restPermission: 'tshock.rest.kill',
    execution: 'rest',
    allowServer: true,
    risk: 'medium',
    description: '击杀一个在线玩家。',
    params: [playerParam()],
    action: 'playerKill',
  },
  {
    id: 'mute',
    title: '禁言玩家',
    command: '/mute',
    category: 'moderation',
    permission: 'tshock.admin.mute',
    execution: 'rest',
    allowServer: true,
    risk: 'medium',
    description: '禁言在线玩家。',
    params: [playerParam()],
    action: 'playerMute',
  },
  {
    id: 'unmute',
    title: '解除禁言',
    command: '/unmute',
    category: 'moderation',
    permission: 'tshock.admin.mute',
    execution: 'rest',
    allowServer: true,
    risk: 'medium',
    description: '解除玩家禁言。',
    params: [playerParam()],
    action: 'playerUnmute',
  },
  {
    id: 'userinfo',
    title: '玩家信息',
    command: '/userinfo',
    aliases: ['/ui'],
    category: 'moderation',
    permission: 'tshock.admin.userinfo',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'low',
    description: '查看玩家信息。',
    params: [playerParam('user', '玩家/账号')],
    rawTemplate: '/userinfo {user}',
    action: 'rawcmd',
  },
  {
    id: 'tempgroup',
    title: '临时改组',
    command: '/tempgroup',
    category: 'users',
    permission: 'tshock.admin.tempgroup',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'high',
    description: '临时设置玩家用户组。',
    params: [
      playerParam(),
      { key: 'group', label: '目标组', type: 'group', required: true },
      { key: 'duration', label: '持续时间', type: 'duration', required: true, default: '1h' },
    ],
    rawTemplate: '/tempgroup {player} {group} {duration}',
    action: 'rawcmd',
  },
  {
    id: 'user-create',
    title: '创建 TShock 用户',
    command: '/user add',
    category: 'users',
    permission: 'tshock.superadmin.user',
    restPermission: 'tshock.rest.users.manage',
    execution: 'rest',
    allowServer: true,
    risk: 'high',
    description: '创建一个 TShock 账号。',
    params: [
      { key: 'user', label: '用户名', type: 'text', required: true },
      { key: 'password', label: '密码', type: 'text', required: true },
      { key: 'group', label: '用户组', type: 'group' },
    ],
    action: 'userCreate',
  },
  {
    id: 'user-update',
    title: '更新 TShock 用户',
    command: '/user group/password',
    category: 'users',
    permission: 'tshock.superadmin.user',
    restPermission: 'tshock.rest.users.manage',
    execution: 'rest',
    allowServer: true,
    risk: 'high',
    description: '修改用户密码或用户组。',
    params: [
      { key: 'user', label: '用户名', type: 'text', required: true },
      { key: 'password', label: '新密码', type: 'text' },
      { key: 'group', label: '用户组', type: 'group' },
    ],
    action: 'userUpdate',
  },
  {
    id: 'user-destroy',
    title: '删除 TShock 用户',
    command: '/user del',
    category: 'users',
    permission: 'tshock.superadmin.user',
    restPermission: 'tshock.rest.users.manage',
    execution: 'rest',
    allowServer: true,
    risk: 'danger',
    description: '删除 TShock 用户账号。',
    params: [{ key: 'user', label: '用户名', type: 'text', required: true }],
    action: 'userDestroy',
  },
  {
    id: 'group-list',
    title: '用户组列表',
    command: '/group list',
    category: 'groups',
    permission: 'tshock.admin.group',
    restPermission: 'tshock.rest.groups.view',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'low',
    description: '列出用户组。',
    rawTemplate: '/group list',
    action: 'rawcmd',
  },
  {
    id: 'group-create',
    title: '创建用户组',
    command: '/group add',
    category: 'groups',
    permission: 'tshock.admin.group',
    restPermission: 'tshock.rest.groups.manage',
    execution: 'rest',
    allowServer: true,
    risk: 'high',
    description: '创建 TShock 用户组。',
    params: [
      { key: 'group', label: '组名', type: 'text', required: true },
      { key: 'parent', label: '父组', type: 'group' },
      { key: 'permissions', label: '权限列表', type: 'permission' },
    ],
    action: 'groupCreate',
  },
  {
    id: 'group-update',
    title: '更新用户组',
    command: '/group addperm/delperm',
    category: 'groups',
    permission: 'tshock.admin.group',
    restPermission: 'tshock.rest.groups.manage',
    execution: 'rest',
    allowServer: true,
    risk: 'high',
    description: '更新用户组父级或权限列表。',
    params: [
      { key: 'group', label: '组名', type: 'group', required: true },
      { key: 'parent', label: '父组', type: 'group' },
      { key: 'permissions', label: '权限列表', type: 'permission' },
    ],
    action: 'groupUpdate',
  },
  {
    id: 'group-destroy',
    title: '删除用户组',
    command: '/group del',
    category: 'groups',
    permission: 'tshock.admin.group',
    restPermission: 'tshock.rest.groups.manage',
    execution: 'rest',
    allowServer: true,
    risk: 'danger',
    description: '删除 TShock 用户组。',
    params: [{ key: 'group', label: '组名', type: 'group', required: true }],
    action: 'groupDestroy',
  },
  {
    id: 'ban-create',
    title: '创建封禁',
    command: '/ban add',
    category: 'bans',
    permission: 'tshock.admin.ban',
    restPermission: 'tshock.rest.bans.manage',
    execution: 'rest',
    allowServer: true,
    risk: 'high',
    description: '按名称或 IP 创建封禁记录。',
    params: [
      { key: 'identifier', label: '玩家名/IP', type: 'text', required: true },
      reasonParam,
      { key: 'duration', label: '持续时间', type: 'duration', placeholder: '例如 1d，留空为永久' },
    ],
    action: 'banCreate',
  },
  {
    id: 'ban-destroy',
    title: '删除封禁',
    command: '/ban del',
    category: 'bans',
    permission: 'tshock.admin.ban',
    restPermission: 'tshock.rest.bans.manage',
    execution: 'rest',
    allowServer: true,
    risk: 'high',
    description: '按 ticket number 删除封禁记录。',
    params: [{ key: 'ticket', label: '封禁票号', type: 'text', required: true }],
    action: 'banDestroy',
  },
  {
    id: 'save',
    title: '保存世界',
    command: '/save',
    category: 'world',
    permission: 'tshock.world.save',
    restPermission: 'tshock.rest.cfg',
    execution: 'rest',
    allowServer: true,
    risk: 'low',
    description: '立即保存世界。',
    action: 'worldSave',
  },
  {
    id: 'world-info',
    title: '世界信息',
    command: '/worldinfo',
    category: 'world',
    permission: 'tshock.world.info',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'low',
    description: '输出当前世界信息。',
    rawTemplate: '/worldinfo',
    action: 'rawcmd',
  },
  {
    id: 'time',
    title: '设置时间',
    command: '/time',
    category: 'world',
    permission: 'tshock.world.time.set',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'medium',
    description: '按 24 小时格式设置世界时间。',
    params: [
      {
        key: 'time',
        label: '时间',
        type: 'time',
        required: true,
        default: '12:00',
        options: [
          { label: '黎明 04:30', value: '04:30' },
          { label: '正午 12:00', value: '12:00' },
          { label: '黄昏 19:30', value: '19:30' },
          { label: '午夜 00:00', value: '00:00' },
        ],
      },
    ],
    rawTemplate: '/time {time}',
    action: 'rawcmd',
  },
  {
    id: 'worldevent',
    title: '世界事件',
    command: '/worldevent',
    category: 'world',
    permission: 'tshock.world.events',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'high',
    description: '启动或切换 TShock 世界事件。',
    params: [
      {
        key: 'event',
        label: '事件',
        type: 'select',
        required: true,
        default: 'bloodmoon',
        options: [
          { label: '血月', value: 'bloodmoon' },
          { label: '满月', value: 'fullmoon' },
          { label: '日食', value: 'eclipse' },
          { label: '下雨', value: 'rain' },
          { label: '沙尘暴', value: 'sandstorm' },
          { label: '灯笼夜', value: 'lanternsnight' },
          { label: '流星雨', value: 'meteorshower' },
          { label: '史莱姆雨', value: 'rain slime' },
          { label: '哥布林入侵', value: 'invasion goblins' },
          { label: '海盗入侵', value: 'invasion pirates' },
          { label: '火星暴乱', value: 'invasion martians' },
          { label: '雪人军团', value: 'invasion snowmen' },
        ],
      },
    ],
    rawTemplate: '/worldevent {event}',
    action: 'rawcmd',
  },
  {
    id: 'wind',
    title: '设置风力',
    command: '/wind',
    category: 'world',
    permission: 'tshock.world.wind',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'medium',
    description: '设置世界风力。',
    params: [{ key: 'speed', label: '风力', type: 'number', required: true, default: 0, min: -1, max: 1 }],
    rawTemplate: '/wind {speed}',
    action: 'rawcmd',
  },
  {
    id: 'butcher',
    title: '清除 NPC',
    command: '/butcher',
    category: 'world',
    permission: 'tshock.npc.butcher',
    restPermission: 'tshock.rest.butcher',
    execution: 'rest',
    allowServer: true,
    risk: 'high',
    description: '清除敌对 NPC，可选择包含友好 NPC。',
    params: [{ key: 'kill_friendly', label: '包含友好 NPC', type: 'boolean', default: false }],
    action: 'worldButcher',
  },
  {
    id: 'bloodmoon-rest',
    title: 'REST 血月开关',
    command: '/world/bloodmoon',
    category: 'world',
    restPermission: 'tshock.rest.causeevents',
    execution: 'rest',
    allowServer: true,
    risk: 'high',
    description: '通过 REST 直接设置血月状态。',
    params: [{ key: 'state', label: '开启血月', type: 'boolean', default: true }],
    action: 'worldBloodmoon',
  },
  {
    id: 'meteor-rest',
    title: '召唤陨石',
    command: '/world/meteor',
    category: 'world',
    restPermission: 'tshock.rest.causeevents',
    execution: 'rest',
    allowServer: true,
    risk: 'high',
    description: '通过 REST 触发陨石。',
    action: 'worldMeteor',
  },
  {
    id: 'autosave',
    title: '自动保存开关',
    command: '/world/autosave',
    category: 'world',
    restPermission: 'tshock.rest.cfg',
    execution: 'rest',
    allowServer: true,
    risk: 'medium',
    description: '开启或关闭 TShock 自动保存。',
    params: [{ key: 'state', label: '开启自动保存', type: 'boolean', default: true }],
    action: 'worldAutosave',
  },
  {
    id: 'hardmode',
    title: '困难模式开关',
    command: '/hardmode',
    category: 'world',
    permission: 'tshock.world.hardmode',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'danger',
    description: '切换世界困难模式。',
    rawTemplate: '/hardmode',
    action: 'rawcmd',
  },
  {
    id: 'worldmode',
    title: '世界难度',
    command: '/worldmode',
    aliases: ['/gamemode'],
    category: 'world',
    permission: 'tshock.world.toggleexpert',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'danger',
    description: '切换世界模式。',
    params: [
      {
        key: 'mode',
        label: '模式',
        type: 'select',
        required: true,
        default: 'expert',
        options: [
          { label: '普通', value: 'normal' },
          { label: '专家', value: 'expert' },
          { label: '大师', value: 'master' },
          { label: '旅途', value: 'journey' },
        ],
      },
    ],
    rawTemplate: '/worldmode {mode}',
    action: 'rawcmd',
  },
  {
    id: 'give',
    title: '发放物品',
    command: '/give',
    aliases: ['/g'],
    category: 'items',
    permission: 'tshock.item.give',
    execution: 'rest',
    allowServer: true,
    risk: 'high',
    description: '给在线玩家发放物品。',
    params: [
      playerParam(),
      { key: 'item', label: '物品', type: 'item', required: true },
      { key: 'stack', label: '数量', type: 'number', required: true, default: 1, min: 1, max: 9999 },
    ],
    action: 'itemGive',
  },
  {
    id: 'gbuff',
    title: '给玩家 Buff',
    command: '/gbuff',
    aliases: ['/buffplayer'],
    category: 'items',
    permission: 'tshock.buff.others',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'medium',
    description: '给指定玩家添加 Buff。',
    params: [
      playerParam(),
      { key: 'buff', label: 'Buff', type: 'buff', required: true, default: 2, placeholder: '选择 Buff / Debuff，或输入 ID' },
      { key: 'duration', label: '持续秒数', type: 'number', required: true, default: 300, min: 1 },
    ],
    rawTemplate: '/gbuff {player} {buff} {duration}',
    action: 'rawcmd',
  },
  {
    id: 'heal',
    title: '治疗玩家',
    command: '/heal',
    category: 'fun',
    permission: 'tshock.heal',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'medium',
    description: '恢复玩家 HP 和 MP。',
    params: [playerParam()],
    rawTemplate: '/heal {player}',
    action: 'rawcmd',
  },
  {
    id: 'godmode',
    title: 'God 模式',
    command: '/godmode',
    aliases: ['/god'],
    category: 'fun',
    permission: 'tshock.godmode',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'high',
    description: '切换玩家 God 模式。',
    params: [playerParam()],
    rawTemplate: '/godmode {player}',
    action: 'rawcmd',
  },
  {
    id: 'slap',
    title: '拍打玩家',
    command: '/slap',
    category: 'fun',
    permission: 'tshock.slap',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'medium',
    description: '拍打玩家并造成指定伤害。',
    params: [playerParam(), { key: 'damage', label: '伤害', type: 'number', default: 0, min: 0 }],
    rawTemplate: '/slap {player} {damage}',
    action: 'rawcmd',
  },
  {
    id: 'annoy',
    title: '骚扰玩家',
    command: '/annoy',
    category: 'fun',
    permission: 'tshock.annoy',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'medium',
    description: '对玩家执行 annoy 效果。',
    params: [playerParam()],
    rawTemplate: '/annoy {player}',
    action: 'rawcmd',
  },
  {
    id: 'rocket',
    title: '火箭玩家',
    command: '/rocket',
    category: 'fun',
    permission: 'tshock.annoy',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'medium',
    description: '将玩家向上发射，通常要求 SSC。',
    params: [playerParam()],
    rawTemplate: '/rocket {player}',
    action: 'rawcmd',
  },
  {
    id: 'serverpassword',
    title: '修改服务器密码',
    command: '/serverpassword',
    category: 'config',
    permission: 'tshock.cfg.password',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'high',
    description: '修改服务器密码。',
    params: [{ key: 'password', label: '新密码', type: 'text', required: true }],
    rawTemplate: '/serverpassword {password}',
    action: 'rawcmd',
  },
  {
    id: 'reload',
    title: '重载配置',
    command: '/reload',
    category: 'config',
    permission: 'tshock.cfg.reload',
    restPermission: 'tshock.rest.cfg',
    execution: 'rest',
    allowServer: true,
    risk: 'high',
    description: '重载 TShock 配置。',
    action: 'serverReload',
  },
  {
    id: 'restart',
    title: 'REST 重启服务器',
    command: '/restart',
    category: 'config',
    permission: 'tshock.cfg.maintenance',
    restPermission: 'tshock.rest.maintenance',
    execution: 'rest',
    allowServer: true,
    risk: 'danger',
    description: '尝试通过 TShock REST 重启服务器。',
    action: 'serverRestart',
  },
  {
    id: 'off',
    title: '关闭服务器',
    command: '/off',
    aliases: ['/exit', '/stop'],
    category: 'config',
    permission: 'tshock.cfg.maintenance',
    restPermission: 'tshock.rest.maintenance',
    execution: 'rest',
    allowServer: true,
    risk: 'danger',
    description: '关闭服务器，可选择不保存。',
    params: [
      { key: 'message', label: '关闭消息', type: 'text' },
      { key: 'nosave', label: '不保存世界', type: 'boolean', default: false },
    ],
    action: 'serverOff',
  },
  {
    id: 'whitelist',
    title: '白名单管理',
    command: '/whitelist',
    category: 'config',
    permission: 'tshock.cfg.whitelist',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'high',
    description: '管理白名单。',
    params: [
      {
        key: 'subcommand',
        label: '操作',
        type: 'select',
        required: true,
        default: 'list',
        options: [
          { label: '列表', value: 'list' },
          { label: '添加', value: 'add' },
          { label: '删除', value: 'del' },
          { label: '启用', value: 'on' },
          { label: '禁用', value: 'off' },
        ],
      },
      { key: 'value', label: '玩家/IP', type: 'text' },
    ],
    rawTemplate: '/whitelist {subcommand} {value}',
    action: 'rawcmd',
  },
  {
    id: 'region',
    title: '区域管理',
    command: '/region',
    category: 'config',
    permission: 'tshock.admin.region',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'high',
    description: '管理区域。设置区域点位需要游戏内上下文，面板适合执行 list/delete/info 等操作。',
    params: [
      {
        key: 'subcommand',
        label: '操作',
        type: 'select',
        required: true,
        default: 'list',
        options: [
          { label: '列表', value: 'list' },
          { label: '信息', value: 'info' },
          { label: '删除', value: 'delete' },
        ],
      },
      { key: 'name', label: '区域名', type: 'text' },
    ],
    rawTemplate: '/region {subcommand} {name}',
    action: 'rawcmd',
  },
  {
    id: 'vanilla-save',
    title: '原版保存世界',
    command: 'save',
    category: 'vanilla',
    execution: 'rawcmd',
    allowServer: true,
    risk: 'low',
    description: '原版服务器控制台保存命令。TShock 推荐使用 /save。',
    rawTemplate: '/save',
    action: 'rawcmd',
  },
  {
    id: 'tp',
    title: '传送到玩家',
    command: '/tp',
    category: 'teleport',
    permission: 'tshock.tp.self',
    execution: 'in_game',
    allowServer: false,
    risk: 'medium',
    description: '传送到目标玩家。',
    params: [playerParam()],
    rawTemplate: '/tp {player}',
    disabledReason: inGameOnly,
  },
  {
    id: 'tphere',
    title: '拉玩家到身边',
    command: '/tphere',
    category: 'teleport',
    permission: 'tshock.tp.others',
    execution: 'in_game',
    allowServer: false,
    risk: 'medium',
    description: '将目标玩家传送到执行者位置。',
    params: [playerParam()],
    rawTemplate: '/tphere {player}',
    disabledReason: inGameOnly,
  },
  {
    id: 'spawnmob',
    title: '生成 NPC',
    command: '/spawnmob',
    aliases: ['/sm'],
    category: 'world',
    permission: 'tshock.npc.spawnmob',
    execution: 'in_game',
    allowServer: false,
    risk: 'high',
    description: '在执行者附近生成 NPC。',
    rawTemplate: '/spawnmob {npc} {count}',
    params: [
      { key: 'npc', label: 'NPC 名称/ID', type: 'text', required: true },
      { key: 'count', label: '数量', type: 'number', default: 1, min: 1 },
    ],
    disabledReason: inGameOnly,
  },
  {
    id: 'spawnboss',
    title: '生成 Boss',
    command: '/spawnboss',
    aliases: ['/sb'],
    category: 'world',
    permission: 'tshock.npc.spawnboss',
    execution: 'in_game',
    allowServer: false,
    risk: 'danger',
    description: '在执行者附近生成 Boss。',
    rawTemplate: '/spawnboss {boss}',
    params: [{ key: 'boss', label: 'Boss 名称/ID', type: 'text', required: true }],
    disabledReason: inGameOnly,
  },
  {
    id: 'grow',
    title: '催生植物',
    command: '/grow',
    category: 'world',
    permission: 'tshock.world.grow',
    execution: 'in_game',
    allowServer: false,
    risk: 'medium',
    description: '在执行者附近催生植物。',
    rawTemplate: '/grow',
    disabledReason: inGameOnly,
  },
  {
    id: 'item-self',
    title: '生成物品到自己',
    command: '/item',
    aliases: ['/i'],
    category: 'items',
    permission: 'tshock.item.spawn',
    execution: 'in_game',
    allowServer: false,
    risk: 'high',
    description: '给执行者生成物品。面板应使用 /give 给指定玩家发放。',
    rawTemplate: '/item {item} {stack}',
    disabledReason: inGameOnly,
  },
]
